#  Test case
#  construct an RDF graph by integrating descriptions from many RDF graphs
#
DESCRIBE ?s 
FROM <http://inference-web.org/registry/AGT/CALO.owl>
FROM <http://inference-web.org/registry/DPR/AFFIR-NEG.owl>
FROM <http://inference-web.org/registry/DPR/AND-Elimination.owl>
FROM <http://inference-web.org/registry/DPR/AND-INTRO.owl>
FROM <http://inference-web.org/registry/DPR/Assumption.owl>
FROM <http://inference-web.org/registry/DPR/AtomicFormulas.owl>
FROM <http://inference-web.org/registry/DPR/Bi-Resolution.owl>
FROM <http://inference-web.org/registry/DPR/BottomLevelTask.owl>
FROM <http://inference-web.org/registry/DPR/CompletedPredecessors.owl>
FROM <http://inference-web.org/registry/DPR/Conjunction.owl>
FROM <http://inference-web.org/registry/DPR/Cut.owl>
FROM <http://inference-web.org/registry/DPR/CWM_Builtin.owl>
FROM <http://inference-web.org/registry/DPR/DataAccess.owl>
FROM <http://inference-web.org/registry/DPR/Demod.owl>
FROM <http://inference-web.org/registry/DPR/EnumeratingProofStep.owl>
FROM <http://inference-web.org/registry/DPR/executing.owl>
FROM <http://inference-web.org/registry/DPR/Extraction.owl>
FROM <http://inference-web.org/registry/DPR/Factoring.owl>
FROM <http://inference-web.org/registry/DPR/FrameMetaInfoReasoningStep.owl>
FROM <http://inference-web.org/registry/DPR/GeronaForwardChaining.owl>
FROM <http://inference-web.org/registry/DPR/GMP.owl>
FROM <http://inference-web.org/registry/DPR/GMPwU.owl>
FROM <http://inference-web.org/registry/DPR/HaveEffectService.owl>
FROM <http://inference-web.org/registry/DPR/Hyp-Resolution.owl>
FROM <http://inference-web.org/registry/DPR/ImplementingProcedureInstance.owl>
FROM <http://inference-web.org/registry/DPR/Inference.owl>
FROM <http://inference-web.org/registry/DPR/InferredValueReasoningStep.owl>
FROM <http://inference-web.org/registry/DPR/InstancePrecondition.owl>
FROM <http://inference-web.org/registry/DPR/IntentionPreconditionMet.owl>
FROM <http://inference-web.org/registry/DPR/Join.owl>
FROM <http://inference-web.org/registry/DPR/MeetServicePostcondition.owl>
FROM <http://inference-web.org/registry/DPR/MeetServicePrecondition.owl>
FROM <http://inference-web.org/registry/DPR/Member.owl>
FROM <http://inference-web.org/registry/DPR/MembershipThruLinkSte.owl>
FROM <http://inference-web.org/registry/DPR/MembershipThruLinkStep.owl>
FROM <http://inference-web.org/registry/DPR/MP.owl>
FROM <http://inference-web.org/registry/DPR/ndImplIntro.owl>
FROM <http://inference-web.org/registry/DPR/ndMPwU.owl>
FROM <http://inference-web.org/registry/DPR/NegConc.owl>
FROM <http://inference-web.org/registry/DPR/Neg-Paramod.owl>
FROM <http://inference-web.org/registry/DPR/NotSuccessful.owl>
FROM <http://inference-web.org/registry/DPR/OR-ELIM.owl>
FROM <http://inference-web.org/registry/DPR/Paramod.owl>
FROM <http://inference-web.org/registry/DPR/ParentSupport.owl>
FROM <http://inference-web.org/registry/DPR/ProcedurePreconditionMet.owl>
FROM <http://inference-web.org/registry/DPR/ProcedurePreconditionsMet.owl>
FROM <http://inference-web.org/registry/DPR/Project.owl>
FROM <http://inference-web.org/registry/DPR/Reformulation.owl>
FROM <http://inference-web.org/registry/DPR/RuleCreationProofStep.owl>
FROM <http://inference-web.org/registry/DPR/RuleInstallationProofStep.owl>
FROM <http://inference-web.org/registry/DPR/Select.owl>
FROM <http://inference-web.org/registry/DPR/SelfSupport.owl>
FROM <http://inference-web.org/registry/DPR/ServiceChainSuccess.owl>
FROM <http://inference-web.org/registry/DPR/Subsump.owl>
FROM <http://inference-web.org/registry/DPR/TaskFinished.owl>
FROM <http://inference-web.org/registry/DPR/TerminationConditionMet.owl>
FROM <http://inference-web.org/registry/DPR/TerminationConditionsNotMet.owl>
FROM <http://inference-web.org/registry/DPR/TimePoint.owl>
FROM <http://inference-web.org/registry/DPR/TimePointMap.owl>
FROM <http://inference-web.org/registry/DPR/Told.owl>
FROM <http://inference-web.org/registry/DPR/TopLevelGoal.owl>
FROM <http://inference-web.org/registry/DPR/TopLevelGoalSupport.owl>
FROM <http://inference-web.org/registry/DPR/TranslationReasoningStep.owl>
FROM <http://inference-web.org/registry/DPR/UD.owl>
FROM <http://inference-web.org/registry/DPR/UI.owl>
FROM <http://inference-web.org/registry/DPR/Unfinished.owl>
FROM <http://inference-web.org/registry/DPR/Union.owl>
FROM <http://inference-web.org/registry/DPR/UNIT-CLAUSES.owl>
FROM <http://inference-web.org/registry/DPR/UNREG.owl>
FROM <http://inference-web.org/registry/DPR/UR-Res.owl>
FROM <http://inference-web.org/registry/DPR/ValueLinkCreationReasoningStep.owl>
FROM <http://inference-web.org/registry/DPR/VCListenerCreationReasoningStep.owl>
FROM <http://inference-web.org/registry/FMT/ascii.owl>
FROM <http://inference-web.org/registry/FMT/bin.owl>
FROM <http://inference-web.org/registry/FMT/ps3.owl>
FROM <http://inference-web.org/registry/IE/CitationTrust.owl>
FROM <http://inference-web.org/registry/IE/contour.owl>
FROM <http://inference-web.org/registry/IE/CWM.owl>
FROM <http://inference-web.org/registry/IE/DCTrain.owl>
FROM <http://inference-web.org/registry/IE/DummyUIM.owl>
FROM <http://inference-web.org/registry/IE/FACT.owl>
FROM <http://inference-web.org/registry/IE/gdrp.owl>
FROM <http://inference-web.org/registry/IE/geonportal.owl>
FROM <http://inference-web.org/registry/IE/Gerona.owl>
FROM <http://inference-web.org/registry/IE/gridder.owl>
FROM <http://inference-web.org/registry/IE/IBMCross-AnnotatorCoreferenceResolver.owl>
FROM <http://inference-web.org/registry/IE/IBMCrossDocumentCoreferenceResolver.owl>
FROM <http://inference-web.org/registry/IE/IBMEAnnotator.owl>
FROM <http://inference-web.org/registry/IE/IBMGlossOnt.owl>
FROM <http://inference-web.org/registry/IE/IBMholdsDuringRelationDetector.owl>
FROM <http://inference-web.org/registry/IE/IBMKnowledgeIntegrator.owl>
FROM <http://inference-web.org/registry/IE/IBMKSRelationDetector.owl>
FROM <http://inference-web.org/registry/IE/IBMmiscTFST.owl>
FROM <http://inference-web.org/registry/IE/IBMstagACE.owl>
FROM <http://inference-web.org/registry/IE/IBMstagKDD.owl>
FROM <http://inference-web.org/registry/IE/IBMtimeTFST.owl>
FROM <http://inference-web.org/registry/IE/ISABELLE.owl>
FROM <http://inference-web.org/registry/IE/JEOPS.owl>
FROM <http://inference-web.org/registry/IE/JESS.owl>
FROM <http://inference-web.org/registry/IE/JResporator.owl>
FROM <http://inference-web.org/registry/IE/JSAT.owl>
FROM <http://inference-web.org/registry/IE/JTP.owl>
FROM <http://inference-web.org/registry/IE/KM.owl>
FROM <http://inference-web.org/registry/IE/Mediator.owl>
FROM <http://inference-web.org/registry/IE/OTTER.owl>
FROM <http://inference-web.org/registry/IE/PowerLoom.owl>
FROM <http://inference-web.org/registry/IE/PTTP.owl>
FROM <http://inference-web.org/registry/IE/RACER.owl>
FROM <http://inference-web.org/registry/IE/RevisionTrust.owl>
FROM <http://inference-web.org/registry/IE/sds.owl>
FROM <http://inference-web.org/registry/IE/SNARK.owl>
FROM <http://inference-web.org/registry/IE/SPARK.owl>
FROM <http://inference-web.org/registry/IE/SWIPL.owl>
FROM <http://inference-web.org/registry/IE/Tailor.owl>
FROM <http://inference-web.org/registry/IE/VAMPIRE.owl>
FROM <http://inference-web.org/registry/LG/ARITHMETIC.owl>
FROM <http://inference-web.org/registry/LG/DAML.owl>
FROM <http://inference-web.org/registry/LG/DATALOG.owl>
FROM <http://inference-web.org/registry/LG/DIMACS.owl>
FROM <http://inference-web.org/registry/LG/English.owl>
FROM <http://inference-web.org/registry/LG/Gerona.owl>
FROM <http://inference-web.org/registry/LG/KIF.owl>
FROM <http://inference-web.org/registry/LG/KM.owl>
FROM <http://inference-web.org/registry/LG/N3.owl>
FROM <http://inference-web.org/registry/LG/PPDR.owl>
FROM <http://inference-web.org/registry/LG/RDF.owl>
FROM <http://inference-web.org/registry/LG/TIME.owl>
FROM <http://inference-web.org/registry/LG/UimaLogic.owl>
FROM <http://inference-web.org/registry/MPR/DCTrainAgentSimulation.owl>
FROM <http://inference-web.org/registry/MPR/DCTrainSensorSimulation.owl>
FROM <http://inference-web.org/registry/MPR/EntityIdentification.owl>
FROM <http://inference-web.org/registry/MPR/EntityMapping.owl>
FROM <http://inference-web.org/registry/MPR/EntityRecognition.owl>
FROM <http://inference-web.org/registry/MPR/ExtractedEntityClassification.owl>
FROM <http://inference-web.org/registry/MPR/Func.owl>
FROM <http://inference-web.org/registry/MPR/genericService.owl>
FROM <http://inference-web.org/registry/MPR/RelationAnnotationArgumentIdentification.owl>
FROM <http://inference-web.org/registry/MPR/RelationIdentification.owl>
FROM <http://inference-web.org/registry/MPR/RelationMapping.owl>
FROM <http://inference-web.org/registry/MPR/RelationRecognition.owl>
FROM <http://inference-web.org/registry/MPR/TargetEntityClassification.owl>
FROM <http://inference-web.org/registry/ONT/AquaSUMO.owl>
FROM <http://inference-web.org/registry/ONT/Computers.owl>
FROM <http://inference-web.org/registry/ONT/CountriesAndRegions.owl>
FROM <http://inference-web.org/registry/ONT/CS4.owl>
FROM <http://inference-web.org/registry/ONT/DAML-EX.owl>
FROM <http://inference-web.org/registry/ONT/DAML-SUMO.owl>
FROM <http://inference-web.org/registry/ONT/FOOD.owl>
FROM <http://inference-web.org/registry/ONT/KIF-Temporal.owl>
FROM <http://inference-web.org/registry/ONT/laptop.owl>
FROM <http://inference-web.org/registry/ONT/Laptops.owl>
FROM <http://inference-web.org/registry/ONT/LoanClasses.owl>
FROM <http://inference-web.org/registry/ONT/nuke.owl>
FROM <http://inference-web.org/registry/ONT/Premise.owl>
FROM <http://inference-web.org/registry/ONT/RDF.owl>
FROM <http://inference-web.org/registry/ONT/STOntology.owl>
FROM <http://inference-web.org/registry/ONT/SUMO.owl>
FROM <http://inference-web.org/registry/ONT/SUMO-RULES.owl>
FROM <http://inference-web.org/registry/ONT/TALIBAN-TEMPORAL.owl>
FROM <http://inference-web.org/registry/ONT/TerroristActs.owl>
FROM <http://inference-web.org/registry/ONT/TerroristAttackTypes.owl>
FROM <http://inference-web.org/registry/ONT/Terrorists.owl>
FROM <http://inference-web.org/registry/ONT/TIME.owl>
FROM <http://inference-web.org/registry/ONT/TonyHallKB.owl>
FROM <http://inference-web.org/registry/ONT/Tonys.owl>
FROM <http://inference-web.org/registry/ONT/Typicality.owl>
FROM <http://inference-web.org/registry/ONT/UNSPSC.owl>
FROM <http://inference-web.org/registry/ONT/WebOnt.owl>
FROM <http://inference-web.org/registry/ONT/WINES.owl>
FROM <http://inference-web.org/registry/ONT/WINES-OWL.owl>
FROM <http://inference-web.org/registry/ONT/WINE-TEST.owl>
FROM <http://inference-web.org/registry/ONT/WMD.owl>
FROM <http://inference-web.org/registry/ORG/ACM.owl>
FROM <http://inference-web.org/registry/ORG/ADDISON-WESLEY.owl>
FROM <http://inference-web.org/registry/ORG/AIC_SRI.owl>
FROM <http://inference-web.org/registry/ORG/AI-ISI.owl>
FROM <http://inference-web.org/registry/ORG/AP.owl>
FROM <http://inference-web.org/registry/ORG/BOEING.owl>
FROM <http://inference-web.org/registry/ORG/CAMBRIDGEPRESS.owl>
FROM <http://inference-web.org/registry/ORG/CIN-UFPE.owl>
FROM <http://inference-web.org/registry/ORG/COMP-CAM.owl>
FROM <http://inference-web.org/registry/ORG/CRIL.owl>
FROM <http://inference-web.org/registry/ORG/CSBERKELEY.owl>
FROM <http://inference-web.org/registry/ORG/CSCMU.owl>
FROM <http://inference-web.org/registry/ORG/CS-CONCORDIA.owl>
FROM <http://inference-web.org/registry/ORG/CS-DUKE.owl>
FROM <http://inference-web.org/registry/ORG/CS-MAN.owl>
FROM <http://inference-web.org/registry/ORG/CS-NYU.owl>
FROM <http://inference-web.org/registry/ORG/CSUTEXAS.owl>
FROM <http://inference-web.org/registry/ORG/DAML-ORG.owl>
FROM <http://inference-web.org/registry/ORG/DAML-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/ELSEVIER.owl>
FROM <http://inference-web.org/registry/ORG/FETCH.owl>
FROM <http://inference-web.org/registry/ORG/GeronaDevelopmentTeam.owl>
FROM <http://inference-web.org/registry/ORG/Gerona-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/GOOGLE.owl>
FROM <http://inference-web.org/registry/ORG/HPLABS.owl>
FROM <http://inference-web.org/registry/ORG/IBM-KSG.owl>
FROM <http://inference-web.org/registry/ORG/IBMRESEARCH.owl>
FROM <http://inference-web.org/registry/ORG/IBM-UIMA.owl>
FROM <http://inference-web.org/registry/ORG/IHMC.owl>
FROM <http://inference-web.org/registry/ORG/ILLC-UvA.owl>
FROM <http://inference-web.org/registry/ORG/ILRT-UBRISTOL.owl>
FROM <http://inference-web.org/registry/ORG/ISA-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/ISI-InfAgents.owl>
FROM <http://inference-web.org/registry/ORG/IW-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/IW-USER.owl>
FROM <http://inference-web.org/registry/ORG/JTP-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/KBS.owl>
FROM <http://inference-web.org/registry/ORG/KM-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/KSL.owl>
FROM <http://inference-web.org/registry/ORG/LOA.owl>
FROM <http://inference-web.org/registry/ORG/MappingTools.owl>
FROM <http://inference-web.org/registry/ORG/MATH-UCSD.owl>
FROM <http://inference-web.org/registry/ORG/MATH-UMUENCHEN.owl>
FROM <http://inference-web.org/registry/ORG/MCS-ARGONNE.owl>
FROM <http://inference-web.org/registry/ORG/NOAA-ORAD.owl>
FROM <http://inference-web.org/registry/ORG/NOKIA-RC.owl>
FROM <http://inference-web.org/registry/ORG/NYT.owl>
FROM <http://inference-web.org/registry/ORG/OBJS.owl>
FROM <http://inference-web.org/registry/ORG/OTTER-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/PACES.owl>
FROM <http://inference-web.org/registry/ORG/Phi-Harvard.owl>
FROM <http://inference-web.org/registry/ORG/PL-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/PRENTICEHALL.owl>
FROM <http://inference-web.org/registry/ORG/RACER-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/RDF-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/SANDIA.owl>
FROM <http://inference-web.org/registry/ORG/SDS-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/SLAC.owl>
FROM <http://inference-web.org/registry/ORG/SNARK-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/SOEST.owl>
FROM <http://inference-web.org/registry/ORG/SPARK.owl>
FROM <http://inference-web.org/registry/ORG/SPRINGER-VERLAG.owl>
FROM <http://inference-web.org/registry/ORG/STANFORD.owl>
FROM <http://inference-web.org/registry/ORG/SWI.owl>
FROM <http://inference-web.org/registry/ORG/SWI-UVA.owl>
FROM <http://inference-web.org/registry/ORG/TAMI-Team.owl>
FROM <http://inference-web.org/registry/ORG/TEKNOWLEDGE.owl>
FROM <http://inference-web.org/registry/ORG/TEK-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/TEK-TEAM-FOR-SUMO.owl>
FROM <http://inference-web.org/registry/ORG/TPG-MUENCHEN.owl>
FROM <http://inference-web.org/registry/ORG/TU-Hamburg.owl>
FROM <http://inference-web.org/registry/ORG/UNIFOR-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/UTEP-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/VAMP-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/W3C.owl>
FROM <http://inference-web.org/registry/ORG/WBS-TEAM.owl>
FROM <http://inference-web.org/registry/ORG/WBS-UKarlsruhe.owl>
FROM <http://inference-web.org/registry/ORG/WISCONSIN-MADISON.owl>
FROM <http://inference-web.org/registry/ORG/XORG.owl>
FROM <http://inference-web.org/registry/PER/Aben.owl>
FROM <http://inference-web.org/registry/PER/AnthonyAppleyard.owl>
FROM <http://inference-web.org/registry/PER/ARiazanov.owl>
FROM <http://inference-web.org/registry/PER/ASTROELSTRA.owl>
FROM <http://inference-web.org/registry/PER/AVoronkov.owl>
FROM <http://inference-web.org/registry/PER/Beland.owl>
FROM <http://inference-web.org/registry/PER/BERNERS-LEE.owl>
FROM <http://inference-web.org/registry/PER/BMACCARTNEY.owl>
FROM <http://inference-web.org/registry/PER/Boguraev.owl>
FROM <http://inference-web.org/registry/PER/BWPORTER.owl>
FROM <http://inference-web.org/registry/PER/CFIGUEIRAFILHO.owl>
FROM <http://inference-web.org/registry/PER/Codd.owl>
FROM <http://inference-web.org/registry/PER/Dan.owl>
FROM <http://inference-web.org/registry/PER/DanMandell.owl>
FROM <http://inference-web.org/registry/PER/DaveFried.owl>
FROM <http://inference-web.org/registry/PER/DavidC.Wilkins.owl>
FROM <http://inference-web.org/registry/PER/DBECKETT.owl>
FROM <http://inference-web.org/registry/PER/DBRICKLEY.owl>
FROM <http://inference-web.org/registry/PER/DCONNOLLY.owl>
FROM <http://inference-web.org/registry/PER/DCTrainUser.owl>
FROM <http://inference-web.org/registry/PER/DFCARSON.owl>
FROM <http://inference-web.org/registry/PER/DLM.owl>
FROM <http://inference-web.org/registry/PER/EFH.owl>
FROM <http://inference-web.org/registry/PER/EMILLER.owl>
FROM <http://inference-web.org/registry/PER/FGLEB.owl>
FROM <http://inference-web.org/registry/PER/FMANOLA.owl>
FROM <http://inference-web.org/registry/PER/Friviere.owl>
FROM <http://inference-web.org/registry/PER/GAROBINSON.owl>
FROM <http://inference-web.org/registry/PER/Gentzen.owl>
FROM <http://inference-web.org/registry/PER/GEONUSR.owl>
FROM <http://inference-web.org/registry/PER/GKLYNE.owl>
FROM <http://inference-web.org/registry/PER/GRAMALHO.owl>
FROM <http://inference-web.org/registry/PER/HChalupsky.owl>
FROM <http://inference-web.org/registry/PER/Honglei.owl>
FROM <http://inference-web.org/registry/PER/HPutnam.owl>
FROM <http://inference-web.org/registry/PER/HSCHWICHTENBERG.owl>
FROM <http://inference-web.org/registry/PER/IHorrocks.owl>
FROM <http://inference-web.org/registry/PER/JCARROLL.owl>
FROM <http://inference-web.org/registry/PER/JGRANT.owl>
FROM <http://inference-web.org/registry/PER/JJENKINS.owl>
FROM <http://inference-web.org/registry/PER/JLAmbite.owl>
FROM <http://inference-web.org/registry/PER/KBALOGLU.owl>
FROM <http://inference-web.org/registry/PER/Knoblock.owl>
FROM <http://inference-web.org/registry/PER/KrzysztofCzuba.owl>
FROM <http://inference-web.org/registry/PER/LeBerre.owl>
FROM <http://inference-web.org/registry/PER/Logemann.owl>
FROM <http://inference-web.org/registry/PER/Loveland.owl>
FROM <http://inference-web.org/registry/PER/LPaulson.owl>
FROM <http://inference-web.org/registry/PER/LSHALLA.owl>
FROM <http://inference-web.org/registry/PER/LWos.owl>
FROM <http://inference-web.org/registry/PER/MaryNeff.owl>
FROM <http://inference-web.org/registry/PER/MDavis.owl>
FROM <http://inference-web.org/registry/PER/MGENESERETH.owl>
FROM <http://inference-web.org/registry/PER/MORLEY.owl>
FROM <http://inference-web.org/registry/PER/Mrcurly.owl>
FROM <http://inference-web.org/registry/PER/MSTICKEL.owl>
FROM <http://inference-web.org/registry/PER/MURDOCK.owl>
FROM <http://inference-web.org/registry/PER/NGuarino.owl>
FROM <http://inference-web.org/registry/PER/OLASSILA.owl>
FROM <http://inference-web.org/registry/PER/OMATLIN.owl>
FROM <http://inference-web.org/registry/PER/PECLARK.owl>
FROM <http://inference-web.org/registry/PER/PHASSE.owl>
FROM <http://inference-web.org/registry/PER/PHAYES.owl>
FROM <http://inference-web.org/registry/PER/PNORVIG.owl>
FROM <http://inference-web.org/registry/PER/PPS.owl>
FROM <http://inference-web.org/registry/PER/PWESSEL.owl>
FROM <http://inference-web.org/registry/PER/QZHOU.owl>
FROM <http://inference-web.org/registry/PER/RFIKES.owl>
FROM <http://inference-web.org/registry/PER/RGUHA.owl>
FROM <http://inference-web.org/registry/PER/RieAndo.owl>
FROM <http://inference-web.org/registry/PER/RLUSK.owl>
FROM <http://inference-web.org/registry/PER/RMcCOOL.owl>
FROM <http://inference-web.org/registry/PER/RMoeller.owl>
FROM <http://inference-web.org/registry/PER/ROVERBEEK.owl>
FROM <http://inference-web.org/registry/PER/RSWICK.owl>
FROM <http://inference-web.org/registry/PER/RWALDINGER.owl>
FROM <http://inference-web.org/registry/PER/SHANDSCHUH.owl>
FROM <http://inference-web.org/registry/PER/SHAWKE.owl>
FROM <http://inference-web.org/registry/PER/SMinton.owl>
FROM <http://inference-web.org/registry/PER/SRBUSS.owl>
FROM <http://inference-web.org/registry/PER/SRUSSELL.owl>
FROM <http://inference-web.org/registry/PER/StefanosDubulakis.owl>
FROM <http://inference-web.org/registry/PER/TNipkow.owl>
FROM <http://inference-web.org/registry/PER/TRUSS.owl>
FROM <http://inference-web.org/registry/PER/TUF-KAT.owl>
FROM <http://inference-web.org/registry/PER/VHaarslev.owl>
FROM <http://inference-web.org/registry/PER/WELTY.owl>
FROM <http://inference-web.org/registry/PER/WIELINGA.owl>
FROM <http://inference-web.org/registry/PER/WMCCUNE.owl>
FROM <http://inference-web.org/registry/PER/WSMITH.owl>
FROM <http://inference-web.org/registry/PER/YoungjaPark.owl>
FROM <http://inference-web.org/registry/PUB/_unzipped_eclipse-SDK-2.owl>
FROM <http://inference-web.org/registry/PUB/Aqua-AP.owl>
FROM <http://inference-web.org/registry/PUB/Aqua-NYT.owl>
FROM <http://inference-web.org/registry/PUB/ARGONNE-RULES.owl>
FROM <http://inference-web.org/registry/PUB/BUSS1998.owl>
FROM <http://inference-web.org/registry/PUB/DavisPutnam1960.owl>
FROM <http://inference-web.org/registry/PUB/DCTrainAgentDescriptions.owl>
FROM <http://inference-web.org/registry/PUB/DCTrainDCAExpertModel.owl>
FROM <http://inference-web.org/registry/PUB/DCTrainDCAOrientation.owl>
FROM <http://inference-web.org/registry/PUB/DCTrainDigitalRepresentation.owl>
FROM <http://inference-web.org/registry/PUB/DCTrainKnowledgeOntology.owl>
FROM <http://inference-web.org/registry/PUB/DCTrainShip.owl>
FROM <http://inference-web.org/registry/PUB/DCXDesign.owl>
FROM <http://inference-web.org/registry/PUB/DLL1962.owl>
FROM <http://inference-web.org/registry/PUB/FIKES.et.al.2003.owl>
FROM <http://inference-web.org/registry/PUB/IBMSampleDocument.owl>
FROM <http://inference-web.org/registry/PUB/McGuinness2003.owl>
FROM <http://inference-web.org/registry/PUB/NavyManual555.owl>
FROM <http://inference-web.org/registry/PUB/NavyManualDDG53.owl>
FROM <http://inference-web.org/registry/PUB/PPDR.owl>
FROM <http://inference-web.org/registry/PUB/RelationalModel.owl>
FROM <http://inference-web.org/registry/PUB/ROBINSON1965.owl>
FROM <http://inference-web.org/registry/PUB/RUSSELLNORVIG1995.owl>
FROM <http://inference-web.org/registry/PUB/STE.owl>
FROM <http://inference-web.org/registry/PUB/SwapTest.owl>
FROM <http://inference-web.org/registry/PUB/SWTUTORIALN3.owl>
FROM <http://inference-web.org/registry/PUB/TrainingCrisisDecisionMaking.owl>
FROM <http://inference-web.org/registry/PUB/TROELSTRA2000.owl>
FROM <http://inference-web.org/registry/PUB/WOSMcCUNE1986.owl>
FROM <http://inference-web.org/registry/PUB/WRCS1967.owl>
WHERE { ?s <http://inference-web.org/2.0/pml-provenance.owl#hasName>  ?o  }