#  Test case
#   select from named graph
#
PREFIX pmlp:      <http://inference-web.org/2.0/pml-provenance.owl#> 
PREFIX rdfs:      <http://www.w3.org/2000/01/rdf-schema#> 
SELECT ?cls 
FROM NAMED  <http://inference-web.org/2.0/pml-provenance.owl> 
WHERE {GRAPH ?g {?cls rdfs:subClassOf  pmlp:Source } }
