/**
 * IW200403.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Fri Sep 04 07:43:02 EDT 2009
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  sw4j.app.pml;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  n/a
 *   	comment:   n/a
 */
public class IW200403{

    protected static final String NS = "http://inferenceweb.stanford.edu/2004/03/iw.owl#";

    public static final String getURI(){ return NS; }

	// Class (24)
	 public final static String VariableMapping_lname = "VariableMapping";
	 public final static String VariableMapping_qname = "iw200403:VariableMapping";
	 public final static String VariableMapping_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#VariableMapping";
	 public final static Resource  VariableMapping = ResourceFactory.createResource(VariableMapping_uri);

	 public final static String InferenceEngine_lname = "InferenceEngine";
	 public final static String InferenceEngine_qname = "iw200403:InferenceEngine";
	 public final static String InferenceEngine_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#InferenceEngine";
	 public final static Resource  InferenceEngine = ResourceFactory.createResource(InferenceEngine_uri);

	 public final static String Person_lname = "Person";
	 public final static String Person_qname = "iw200403:Person";
	 public final static String Person_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Person";
	 public final static Resource  Person = ResourceFactory.createResource(Person_uri);

	 public final static String ProvenanceElement_lname = "ProvenanceElement";
	 public final static String ProvenanceElement_qname = "iw200403:ProvenanceElement";
	 public final static String ProvenanceElement_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#ProvenanceElement";
	 public final static Resource  ProvenanceElement = ResourceFactory.createResource(ProvenanceElement_uri);

	 public final static String TranslationRule_lname = "TranslationRule";
	 public final static String TranslationRule_qname = "iw200403:TranslationRule";
	 public final static String TranslationRule_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#TranslationRule";
	 public final static Resource  TranslationRule = ResourceFactory.createResource(TranslationRule_uri);

	 public final static String Organization_lname = "Organization";
	 public final static String Organization_qname = "iw200403:Organization";
	 public final static String Organization_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Organization";
	 public final static Resource  Organization = ResourceFactory.createResource(Organization_uri);

	 public final static String InferenceStep_lname = "InferenceStep";
	 public final static String InferenceStep_qname = "iw200403:InferenceStep";
	 public final static String InferenceStep_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#InferenceStep";
	 public final static Resource  InferenceStep = ResourceFactory.createResource(InferenceStep_uri);

	 public final static String PrimitiveRule_lname = "PrimitiveRule";
	 public final static String PrimitiveRule_qname = "iw200403:PrimitiveRule";
	 public final static String PrimitiveRule_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#PrimitiveRule";
	 public final static Resource  PrimitiveRule = ResourceFactory.createResource(PrimitiveRule_uri);

	 public final static String Question_lname = "Question";
	 public final static String Question_qname = "iw200403:Question";
	 public final static String Question_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Question";
	 public final static Resource  Question = ResourceFactory.createResource(Question_uri);

	 public final static String Source_lname = "Source";
	 public final static String Source_qname = "iw200403:Source";
	 public final static String Source_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Source";
	 public final static Resource  Source = ResourceFactory.createResource(Source_uri);

	 public final static String MethodRule_lname = "MethodRule";
	 public final static String MethodRule_qname = "iw200403:MethodRule";
	 public final static String MethodRule_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#MethodRule";
	 public final static Resource  MethodRule = ResourceFactory.createResource(MethodRule_uri);

	 public final static String Team_lname = "Team";
	 public final static String Team_qname = "iw200403:Team";
	 public final static String Team_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Team";
	 public final static Resource  Team = ResourceFactory.createResource(Team_uri);

	 public final static String ProofElement_lname = "ProofElement";
	 public final static String ProofElement_qname = "iw200403:ProofElement";
	 public final static String ProofElement_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#ProofElement";
	 public final static Resource  ProofElement = ResourceFactory.createResource(ProofElement_uri);

	 public final static String NodeSet_lname = "NodeSet";
	 public final static String NodeSet_qname = "iw200403:NodeSet";
	 public final static String NodeSet_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#NodeSet";
	 public final static Resource  NodeSet = ResourceFactory.createResource(NodeSet_uri);

	 public final static String LanguageAxiomSet_lname = "LanguageAxiomSet";
	 public final static String LanguageAxiomSet_qname = "iw200403:LanguageAxiomSet";
	 public final static String LanguageAxiomSet_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#LanguageAxiomSet";
	 public final static Resource  LanguageAxiomSet = ResourceFactory.createResource(LanguageAxiomSet_uri);

	 public final static String Ontology_lname = "Ontology";
	 public final static String Ontology_qname = "iw200403:Ontology";
	 public final static String Ontology_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Ontology";
	 public final static Resource  Ontology = ResourceFactory.createResource(Ontology_uri);

	 public final static String Publication_lname = "Publication";
	 public final static String Publication_qname = "iw200403:Publication";
	 public final static String Publication_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Publication";
	 public final static Resource  Publication = ResourceFactory.createResource(Publication_uri);

	 public final static String Query_lname = "Query";
	 public final static String Query_qname = "iw200403:Query";
	 public final static String Query_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Query";
	 public final static Resource  Query = ResourceFactory.createResource(Query_uri);

	 public final static String DerivedRule_lname = "DerivedRule";
	 public final static String DerivedRule_qname = "iw200403:DerivedRule";
	 public final static String DerivedRule_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#DerivedRule";
	 public final static Resource  DerivedRule = ResourceFactory.createResource(DerivedRule_uri);

	 public final static String DeclarativeRule_lname = "DeclarativeRule";
	 public final static String DeclarativeRule_qname = "iw200403:DeclarativeRule";
	 public final static String DeclarativeRule_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#DeclarativeRule";
	 public final static Resource  DeclarativeRule = ResourceFactory.createResource(DeclarativeRule_uri);

	 public final static String InferenceRule_lname = "InferenceRule";
	 public final static String InferenceRule_qname = "iw200403:InferenceRule";
	 public final static String InferenceRule_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#InferenceRule";
	 public final static Resource  InferenceRule = ResourceFactory.createResource(InferenceRule_uri);

	 public final static String ModelElement_lname = "ModelElement";
	 public final static String ModelElement_qname = "iw200403:ModelElement";
	 public final static String ModelElement_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#ModelElement";
	 public final static Resource  ModelElement = ResourceFactory.createResource(ModelElement_uri);

	 public final static String Axiom_lname = "Axiom";
	 public final static String Axiom_qname = "iw200403:Axiom";
	 public final static String Axiom_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Axiom";
	 public final static Resource  Axiom = ResourceFactory.createResource(Axiom_uri);

	 public final static String Language_lname = "Language";
	 public final static String Language_qname = "iw200403:Language";
	 public final static String Language_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#Language";
	 public final static Resource  Language = ResourceFactory.createResource(Language_uri);

	// Property (50)
	 public final static String hasRule_lname = "hasRule";
	 public final static String hasRule_qname = "iw200403:hasRule";
	 public final static String hasRule_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasRule";
	 public final static Property  hasRule = ResourceFactory.createProperty(hasRule_uri);

	 public final static String lastSubmissionDate_lname = "lastSubmissionDate";
	 public final static String lastSubmissionDate_qname = "iw200403:lastSubmissionDate";
	 public final static String lastSubmissionDate_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#lastSubmissionDate";
	 public final static Property  lastSubmissionDate = ResourceFactory.createProperty(lastSubmissionDate_uri);

	 public final static String hasAxiom_lname = "hasAxiom";
	 public final static String hasAxiom_qname = "iw200403:hasAxiom";
	 public final static String hasAxiom_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasAxiom";
	 public final static Property  hasAxiom = ResourceFactory.createProperty(hasAxiom_uri);

	 public final static String fromLanguage_lname = "fromLanguage";
	 public final static String fromLanguage_qname = "iw200403:fromLanguage";
	 public final static String fromLanguage_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#fromLanguage";
	 public final static Property  fromLanguage = ResourceFactory.createProperty(fromLanguage_uri);

	 public final static String isFromEngine_lname = "isFromEngine";
	 public final static String isFromEngine_qname = "iw200403:isFromEngine";
	 public final static String isFromEngine_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#isFromEngine";
	 public final static Property  isFromEngine = ResourceFactory.createProperty(isFromEngine_uri);

	 public final static String hasDischarge_lname = "hasDischarge";
	 public final static String hasDischarge_qname = "iw200403:hasDischarge";
	 public final static String hasDischarge_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasDischarge";
	 public final static Property  hasDischarge = ResourceFactory.createProperty(hasDischarge_uri);

	 public final static String version_lname = "version";
	 public final static String version_qname = "iw200403:version";
	 public final static String version_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#version";
	 public final static Property  version = ResourceFactory.createProperty(version_uri);

	 public final static String toLanguage_lname = "toLanguage";
	 public final static String toLanguage_qname = "iw200403:toLanguage";
	 public final static String toLanguage_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#toLanguage";
	 public final static Property  toLanguage = ResourceFactory.createProperty(toLanguage_uri);

	 public final static String variable_lname = "variable";
	 public final static String variable_qname = "iw200403:variable";
	 public final static String variable_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#variable";
	 public final static Property  variable = ResourceFactory.createProperty(variable_uri);

	 public final static String ruleSpec_lname = "ruleSpec";
	 public final static String ruleSpec_qname = "iw200403:ruleSpec";
	 public final static String ruleSpec_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#ruleSpec";
	 public final static Property  ruleSpec = ResourceFactory.createProperty(ruleSpec_uri);

	 public final static String month_lname = "month";
	 public final static String month_qname = "iw200403:month";
	 public final static String month_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#month";
	 public final static Property  month = ResourceFactory.createProperty(month_uri);

	 public final static String fromExpresssion_lname = "fromExpresssion";
	 public final static String fromExpresssion_qname = "iw200403:fromExpresssion";
	 public final static String fromExpresssion_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#fromExpresssion";
	 public final static Property  fromExpresssion = ResourceFactory.createProperty(fromExpresssion_uri);

	 public final static String toExpression_lname = "toExpression";
	 public final static String toExpression_qname = "iw200403:toExpression";
	 public final static String toExpression_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#toExpression";
	 public final static Property  toExpression = ResourceFactory.createProperty(toExpression_uri);

	 public final static String forLanguage_lname = "forLanguage";
	 public final static String forLanguage_qname = "iw200403:forLanguage";
	 public final static String forLanguage_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#forLanguage";
	 public final static Property  forLanguage = ResourceFactory.createProperty(forLanguage_uri);

	 public final static String hasLanguage_lname = "hasLanguage";
	 public final static String hasLanguage_qname = "iw200403:hasLanguage";
	 public final static String hasLanguage_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasLanguage";
	 public final static Property  hasLanguage = ResourceFactory.createProperty(hasLanguage_uri);

	 public final static String isConsequentOf_lname = "isConsequentOf";
	 public final static String isConsequentOf_qname = "iw200403:isConsequentOf";
	 public final static String isConsequentOf_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#isConsequentOf";
	 public final static Property  isConsequentOf = ResourceFactory.createProperty(isConsequentOf_uri);

	 public final static String verificationMethod_lname = "verificationMethod";
	 public final static String verificationMethod_qname = "iw200403:verificationMethod";
	 public final static String verificationMethod_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#verificationMethod";
	 public final static Property  verificationMethod = ResourceFactory.createProperty(verificationMethod_uri);

	 public final static String hasOntology_lname = "hasOntology";
	 public final static String hasOntology_qname = "iw200403:hasOntology";
	 public final static String hasOntology_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasOntology";
	 public final static Property  hasOntology = ResourceFactory.createProperty(hasOntology_uri);

	 public final static String hasVariableMapping_lname = "hasVariableMapping";
	 public final static String hasVariableMapping_qname = "iw200403:hasVariableMapping";
	 public final static String hasVariableMapping_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasVariableMapping";
	 public final static Property  hasVariableMapping = ResourceFactory.createProperty(hasVariableMapping_uri);

	 public final static String inferenceEngineRule_lname = "inferenceEngineRule";
	 public final static String inferenceEngineRule_qname = "iw200403:inferenceEngineRule";
	 public final static String inferenceEngineRule_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#inferenceEngineRule";
	 public final static Property  inferenceEngineRule = ResourceFactory.createProperty(inferenceEngineRule_uri);

	 public final static String englishExample_lname = "englishExample";
	 public final static String englishExample_qname = "iw200403:englishExample";
	 public final static String englishExample_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#englishExample";
	 public final static Property  englishExample = ResourceFactory.createProperty(englishExample_uri);

	 public final static String day_lname = "day";
	 public final static String day_qname = "iw200403:day";
	 public final static String day_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#day";
	 public final static Property  day = ResourceFactory.createProperty(day_uri);

	 public final static String uri_lname = "uri";
	 public final static String uri_qname = "iw200403:uri";
	 public final static String uri_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#uri";
	 public final static Property  uri = ResourceFactory.createProperty(uri_uri);

	 public final static String url_lname = "url";
	 public final static String url_qname = "iw200403:url";
	 public final static String url_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#url";
	 public final static Property  url = ResourceFactory.createProperty(url_uri);

	 public final static String axiomContent_lname = "axiomContent";
	 public final static String axiomContent_qname = "iw200403:axiomContent";
	 public final static String axiomContent_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#axiomContent";
	 public final static Property  axiomContent = ResourceFactory.createProperty(axiomContent_uri);

	 public final static String englishDescription_lname = "englishDescription";
	 public final static String englishDescription_qname = "iw200403:englishDescription";
	 public final static String englishDescription_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#englishDescription";
	 public final static Property  englishDescription = ResourceFactory.createProperty(englishDescription_uri);

	 public final static String hasInferenceEngine_lname = "hasInferenceEngine";
	 public final static String hasInferenceEngine_qname = "iw200403:hasInferenceEngine";
	 public final static String hasInferenceEngine_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasInferenceEngine";
	 public final static Property  hasInferenceEngine = ResourceFactory.createProperty(hasInferenceEngine_uri);

	 public final static String conclusion_lname = "conclusion";
	 public final static String conclusion_qname = "iw200403:conclusion";
	 public final static String conclusion_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#conclusion";
	 public final static Property  conclusion = ResourceFactory.createProperty(conclusion_uri);

	 public final static String hasAuthor_lname = "hasAuthor";
	 public final static String hasAuthor_qname = "iw200403:hasAuthor";
	 public final static String hasAuthor_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasAuthor";
	 public final static Property  hasAuthor = ResourceFactory.createProperty(hasAuthor_uri);

	 public final static String tacticOfAxiom_lname = "tacticOfAxiom";
	 public final static String tacticOfAxiom_qname = "iw200403:tacticOfAxiom";
	 public final static String tacticOfAxiom_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#tacticOfAxiom";
	 public final static Property  tacticOfAxiom = ResourceFactory.createProperty(tacticOfAxiom_uri);

	 public final static String queryContent_lname = "queryContent";
	 public final static String queryContent_qname = "iw200403:queryContent";
	 public final static String queryContent_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#queryContent";
	 public final static Property  queryContent = ResourceFactory.createProperty(queryContent_uri);

	 public final static String hasAntecedent_lname = "hasAntecedent";
	 public final static String hasAntecedent_qname = "iw200403:hasAntecedent";
	 public final static String hasAntecedent_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasAntecedent";
	 public final static Property  hasAntecedent = ResourceFactory.createProperty(hasAntecedent_uri);

	 public final static String date_lname = "date";
	 public final static String date_qname = "iw200403:date";
	 public final static String date_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#date";
	 public final static Property  date = ResourceFactory.createProperty(date_uri);

	 public final static String hasMember_lname = "hasMember";
	 public final static String hasMember_qname = "iw200403:hasMember";
	 public final static String hasMember_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasMember";
	 public final static Property  hasMember = ResourceFactory.createProperty(hasMember_uri);

	 public final static String year_lname = "year";
	 public final static String year_qname = "iw200403:year";
	 public final static String year_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#year";
	 public final static Property  year = ResourceFactory.createProperty(year_uri);

	 public final static String firstSubmissionDate_lname = "firstSubmissionDate";
	 public final static String firstSubmissionDate_qname = "iw200403:firstSubmissionDate";
	 public final static String firstSubmissionDate_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#firstSubmissionDate";
	 public final static Property  firstSubmissionDate = ResourceFactory.createProperty(firstSubmissionDate_uri);

	 public final static String submitter_lname = "submitter";
	 public final static String submitter_qname = "iw200403:submitter";
	 public final static String submitter_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#submitter";
	 public final static Property  submitter = ResourceFactory.createProperty(submitter_uri);

	 public final static String hasAnswerPattern_lname = "hasAnswerPattern";
	 public final static String hasAnswerPattern_qname = "iw200403:hasAnswerPattern";
	 public final static String hasAnswerPattern_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasAnswerPattern";
	 public final static Property  hasAnswerPattern = ResourceFactory.createProperty(hasAnswerPattern_uri);

	 public final static String englishDescriptionTemplate_lname = "englishDescriptionTemplate";
	 public final static String englishDescriptionTemplate_qname = "iw200403:englishDescriptionTemplate";
	 public final static String englishDescriptionTemplate_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#englishDescriptionTemplate";
	 public final static Property  englishDescriptionTemplate = ResourceFactory.createProperty(englishDescriptionTemplate_uri);

	 public final static String hasAnswer_lname = "hasAnswer";
	 public final static String hasAnswer_qname = "iw200403:hasAnswer";
	 public final static String hasAnswer_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasAnswer";
	 public final static Property  hasAnswer = ResourceFactory.createProperty(hasAnswer_uri);

	 public final static String isExplanationOf_lname = "isExplanationOf";
	 public final static String isExplanationOf_qname = "iw200403:isExplanationOf";
	 public final static String isExplanationOf_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#isExplanationOf";
	 public final static Property  isExplanationOf = ResourceFactory.createProperty(isExplanationOf_uri);

	 public final static String escapeCharacter_lname = "escapeCharacter";
	 public final static String escapeCharacter_qname = "iw200403:escapeCharacter";
	 public final static String escapeCharacter_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#escapeCharacter";
	 public final static Property  escapeCharacter = ResourceFactory.createProperty(escapeCharacter_uri);

	 public final static String isQueryFor_lname = "isQueryFor";
	 public final static String isQueryFor_qname = "iw200403:isQueryFor";
	 public final static String isQueryFor_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#isQueryFor";
	 public final static Property  isQueryFor = ResourceFactory.createProperty(isQueryFor_uri);

	 public final static String term_lname = "term";
	 public final static String term_qname = "iw200403:term";
	 public final static String term_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#term";
	 public final static Property  term = ResourceFactory.createProperty(term_uri);

	 public final static String fromQuery_lname = "fromQuery";
	 public final static String fromQuery_qname = "iw200403:fromQuery";
	 public final static String fromQuery_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#fromQuery";
	 public final static Property  fromQuery = ResourceFactory.createProperty(fromQuery_uri);

	 public final static String name_lname = "name";
	 public final static String name_qname = "iw200403:name";
	 public final static String name_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#name";
	 public final static Property  name = ResourceFactory.createProperty(name_uri);

	 public final static String hasSource_lname = "hasSource";
	 public final static String hasSource_qname = "iw200403:hasSource";
	 public final static String hasSource_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#hasSource";
	 public final static Property  hasSource = ResourceFactory.createProperty(hasSource_uri);

	 public final static String questionContent_lname = "questionContent";
	 public final static String questionContent_qname = "iw200403:questionContent";
	 public final static String questionContent_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#questionContent";
	 public final static Property  questionContent = ResourceFactory.createProperty(questionContent_uri);

	 public final static String describedFrom_lname = "describedFrom";
	 public final static String describedFrom_qname = "iw200403:describedFrom";
	 public final static String describedFrom_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#describedFrom";
	 public final static Property  describedFrom = ResourceFactory.createProperty(describedFrom_uri);

	 public final static String fromAnswer_lname = "fromAnswer";
	 public final static String fromAnswer_qname = "iw200403:fromAnswer";
	 public final static String fromAnswer_uri = "http://inferenceweb.stanford.edu/2004/03/iw.owl#fromAnswer";
	 public final static Property  fromAnswer = ResourceFactory.createProperty(fromAnswer_uri);

	// Instance (0)


}


 
