/**
 * PMLOWL.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Tue Sep 15 14:27:34 EDT 2009
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  sw4j.app.pml;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  PML2 owl extension@en
 *   	comment:   The owl extension of PML2 ontology. It extends some concepts in PMLP @en
 */
public class PMLOWL{

    protected static final String NS = "http://inference-web.org/2.0/pml-owl.owl#";

    public static final String getURI(){ return NS; }

	// Class (1)
	 public final static String InformationRdfInstance_lname = "InformationRdfInstance";
	 public final static String InformationRdfInstance_qname = "pmlowl:InformationRdfInstance";
	 public final static String InformationRdfInstance_uri = "http://inference-web.org/2.0/pml-owl.owl#InformationRdfInstance";
	 public final static Resource  InformationRdfInstance = ResourceFactory.createResource(InformationRdfInstance_uri);

	// Property (13)
	 public final static String hasDiffUpdateInstance_lname = "hasDiffUpdateInstance";
	 public final static String hasDiffUpdateInstance_qname = "pmlowl:hasDiffUpdateInstance";
	 public final static String hasDiffUpdateInstance_uri = "http://inference-web.org/2.0/pml-owl.owl#hasDiffUpdateInstance";
	 public final static Property  hasDiffUpdateInstance = ResourceFactory.createProperty(hasDiffUpdateInstance_uri);

	 public final static String hasDiffUpdateInstanceUpdateProperty_lname = "hasDiffUpdateInstanceUpdateProperty";
	 public final static String hasDiffUpdateInstanceUpdateProperty_qname = "pmlowl:hasDiffUpdateInstanceUpdateProperty";
	 public final static String hasDiffUpdateInstanceUpdateProperty_uri = "http://inference-web.org/2.0/pml-owl.owl#hasDiffUpdateInstanceUpdateProperty";
	 public final static Property  hasDiffUpdateInstanceUpdateProperty = ResourceFactory.createProperty(hasDiffUpdateInstanceUpdateProperty_uri);

	 public final static String hasInstanceType_lname = "hasInstanceType";
	 public final static String hasInstanceType_qname = "pmlowl:hasInstanceType";
	 public final static String hasInstanceType_uri = "http://inference-web.org/2.0/pml-owl.owl#hasInstanceType";
	 public final static Property  hasInstanceType = ResourceFactory.createProperty(hasInstanceType_uri);

	 public final static String hasDiffSourcePrev_lname = "hasDiffSourcePrev";
	 public final static String hasDiffSourcePrev_qname = "pmlowl:hasDiffSourcePrev";
	 public final static String hasDiffSourcePrev_uri = "http://inference-web.org/2.0/pml-owl.owl#hasDiffSourcePrev";
	 public final static Property  hasDiffSourcePrev = ResourceFactory.createProperty(hasDiffSourcePrev_uri);

	 public final static String hasSubjectReference_lname = "hasSubjectReference";
	 public final static String hasSubjectReference_qname = "pmlowl:hasSubjectReference";
	 public final static String hasSubjectReference_uri = "http://inference-web.org/2.0/pml-owl.owl#hasSubjectReference";
	 public final static Property  hasSubjectReference = ResourceFactory.createProperty(hasSubjectReference_uri);

	 public final static String hasDiffSourceCur_lname = "hasDiffSourceCur";
	 public final static String hasDiffSourceCur_qname = "pmlowl:hasDiffSourceCur";
	 public final static String hasDiffSourceCur_uri = "http://inference-web.org/2.0/pml-owl.owl#hasDiffSourceCur";
	 public final static Property  hasDiffSourceCur = ResourceFactory.createProperty(hasDiffSourceCur_uri);

	 public final static String hasDiffDelInstance_lname = "hasDiffDelInstance";
	 public final static String hasDiffDelInstance_qname = "pmlowl:hasDiffDelInstance";
	 public final static String hasDiffDelInstance_uri = "http://inference-web.org/2.0/pml-owl.owl#hasDiffDelInstance";
	 public final static Property  hasDiffDelInstance = ResourceFactory.createProperty(hasDiffDelInstance_uri);

	 public final static String hasInstanceReference_lname = "hasInstanceReference";
	 public final static String hasInstanceReference_qname = "pmlowl:hasInstanceReference";
	 public final static String hasInstanceReference_uri = "http://inference-web.org/2.0/pml-owl.owl#hasInstanceReference";
	 public final static Property  hasInstanceReference = ResourceFactory.createProperty(hasInstanceReference_uri);

	 public final static String hasPropertyReference_lname = "hasPropertyReference";
	 public final static String hasPropertyReference_qname = "pmlowl:hasPropertyReference";
	 public final static String hasPropertyReference_uri = "http://inference-web.org/2.0/pml-owl.owl#hasPropertyReference";
	 public final static Property  hasPropertyReference = ResourceFactory.createProperty(hasPropertyReference_uri);

	 public final static String hasDiffUpdateInstanceAddProperty_lname = "hasDiffUpdateInstanceAddProperty";
	 public final static String hasDiffUpdateInstanceAddProperty_qname = "pmlowl:hasDiffUpdateInstanceAddProperty";
	 public final static String hasDiffUpdateInstanceAddProperty_uri = "http://inference-web.org/2.0/pml-owl.owl#hasDiffUpdateInstanceAddProperty";
	 public final static Property  hasDiffUpdateInstanceAddProperty = ResourceFactory.createProperty(hasDiffUpdateInstanceAddProperty_uri);

	 public final static String hasDiffUpdateInstanceDelProperty_lname = "hasDiffUpdateInstanceDelProperty";
	 public final static String hasDiffUpdateInstanceDelProperty_qname = "pmlowl:hasDiffUpdateInstanceDelProperty";
	 public final static String hasDiffUpdateInstanceDelProperty_uri = "http://inference-web.org/2.0/pml-owl.owl#hasDiffUpdateInstanceDelProperty";
	 public final static Property  hasDiffUpdateInstanceDelProperty = ResourceFactory.createProperty(hasDiffUpdateInstanceDelProperty_uri);

	 public final static String hasDiffAddInstance_lname = "hasDiffAddInstance";
	 public final static String hasDiffAddInstance_qname = "pmlowl:hasDiffAddInstance";
	 public final static String hasDiffAddInstance_uri = "http://inference-web.org/2.0/pml-owl.owl#hasDiffAddInstance";
	 public final static Property  hasDiffAddInstance = ResourceFactory.createProperty(hasDiffAddInstance_uri);

	 public final static String hasDiffRelation_lname = "hasDiffRelation";
	 public final static String hasDiffRelation_qname = "pmlowl:hasDiffRelation";
	 public final static String hasDiffRelation_uri = "http://inference-web.org/2.0/pml-owl.owl#hasDiffRelation";
	 public final static Property  hasDiffRelation = ResourceFactory.createProperty(hasDiffRelation_uri);

	// Instance (0)


}


 
