/**
 * PMLOWL.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Thu Apr 24 10:49:56 EDT 2008
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  sw4j.vocabulary;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  PML2 owl extension@en
 *   	comment:   The owl extension of PML2 ontology. It extends some concepts in PMLP @en
 */
public class PMLOWL{

    protected static final String NS = "http://inference-web.org/2.0/pml-owl.owl#";

    public static final String getURI(){ return NS; }

	// Class (1)
	 public final static String InformationRdfInstance_lname = "InformationRdfInstance";
	 public final static String InformationRdfInstance_qname = "pmlowl:InformationRdfInstance";
	 public final static String InformationRdfInstance_uri = "http://inference-web.org/2.0/pml-owl.owl#InformationRdfInstance";
	 public final static Resource  InformationRdfInstance = ResourceFactory.createResource(InformationRdfInstance_uri);

	// Property (1)
	 public final static String hasInstanceReference_lname = "hasInstanceReference";
	 public final static String hasInstanceReference_qname = "pmlowl:hasInstanceReference";
	 public final static String hasInstanceReference_uri = "http://inference-web.org/2.0/pml-owl.owl#hasInstanceReference";
	 public final static Property  hasInstanceReference = ResourceFactory.createProperty(hasInstanceReference_uri);

	// Instance (0)


}


 
