/**
 * IW200407.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Tue Sep 15 14:27:35 EDT 2009
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  sw4j.app.pml;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  IW200407V3@en
 *   	comment:   PML ontology. This includes small updates from the July 2004 PML ontology.@en
 */
public class IW200407{

    protected static final String NS = "http://inferenceweb.stanford.edu/2004/07/iw.owl#";

    public static final String getURI(){ return NS; }

	// Class (33)
	 public final static String Ontology_lname = "Ontology";
	 public final static String Ontology_qname = "iw200407:Ontology";
	 public final static String Ontology_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Ontology";
	 public final static Resource  Ontology = ResourceFactory.createResource(Ontology_uri);

	 public final static String Person_lname = "Person";
	 public final static String Person_qname = "iw200407:Person";
	 public final static String Person_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Person";
	 public final static Resource  Person = ResourceFactory.createResource(Person_uri);

	 public final static String Axiom_lname = "Axiom";
	 public final static String Axiom_qname = "iw200407:Axiom";
	 public final static String Axiom_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Axiom";
	 public final static Resource  Axiom = ResourceFactory.createResource(Axiom_uri);

	 public final static String ProvenanceElement_lname = "ProvenanceElement";
	 public final static String ProvenanceElement_qname = "iw200407:ProvenanceElement";
	 public final static String ProvenanceElement_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#ProvenanceElement";
	 public final static Resource  ProvenanceElement = ResourceFactory.createResource(ProvenanceElement_uri);

	 public final static String InferenceEngine_lname = "InferenceEngine";
	 public final static String InferenceEngine_qname = "iw200407:InferenceEngine";
	 public final static String InferenceEngine_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#InferenceEngine";
	 public final static Resource  InferenceEngine = ResourceFactory.createResource(InferenceEngine_uri);

	 public final static String Format_lname = "Format";
	 public final static String Format_qname = "iw200407:Format";
	 public final static String Format_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Format";
	 public final static Resource  Format = ResourceFactory.createResource(Format_uri);

	 public final static String Language_lname = "Language";
	 public final static String Language_qname = "iw200407:Language";
	 public final static String Language_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Language";
	 public final static Resource  Language = ResourceFactory.createResource(Language_uri);

	 public final static String Website_lname = "Website";
	 public final static String Website_qname = "iw200407:Website";
	 public final static String Website_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Website";
	 public final static Resource  Website = ResourceFactory.createResource(Website_uri);

	 public final static String AggregatedTrustRelation_lname = "AggregatedTrustRelation";
	 public final static String AggregatedTrustRelation_qname = "iw200407:AggregatedTrustRelation";
	 public final static String AggregatedTrustRelation_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#AggregatedTrustRelation";
	 public final static Resource  AggregatedTrustRelation = ResourceFactory.createResource(AggregatedTrustRelation_uri);

	 public final static String Team_lname = "Team";
	 public final static String Team_qname = "iw200407:Team";
	 public final static String Team_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Team";
	 public final static Resource  Team = ResourceFactory.createResource(Team_uri);

	 public final static String NodeSet_lname = "NodeSet";
	 public final static String NodeSet_qname = "iw200407:NodeSet";
	 public final static String NodeSet_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#NodeSet";
	 public final static Resource  NodeSet = ResourceFactory.createResource(NodeSet_uri);

	 public final static String InferenceStep_lname = "InferenceStep";
	 public final static String InferenceStep_qname = "iw200407:InferenceStep";
	 public final static String InferenceStep_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#InferenceStep";
	 public final static Resource  InferenceStep = ResourceFactory.createResource(InferenceStep_uri);

	 public final static String Publication_lname = "Publication";
	 public final static String Publication_qname = "iw200407:Publication";
	 public final static String Publication_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Publication";
	 public final static Resource  Publication = ResourceFactory.createResource(Publication_uri);

	 public final static String Question_lname = "Question";
	 public final static String Question_qname = "iw200407:Question";
	 public final static String Question_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Question";
	 public final static Resource  Question = ResourceFactory.createResource(Question_uri);

	 public final static String Source_lname = "Source";
	 public final static String Source_qname = "iw200407:Source";
	 public final static String Source_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Source";
	 public final static Resource  Source = ResourceFactory.createResource(Source_uri);

	 public final static String Query_lname = "Query";
	 public final static String Query_qname = "iw200407:Query";
	 public final static String Query_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Query";
	 public final static Resource  Query = ResourceFactory.createResource(Query_uri);

	 public final static String PrettyNameMapping_lname = "PrettyNameMapping";
	 public final static String PrettyNameMapping_qname = "iw200407:PrettyNameMapping";
	 public final static String PrettyNameMapping_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#PrettyNameMapping";
	 public final static Resource  PrettyNameMapping = ResourceFactory.createResource(PrettyNameMapping_uri);

	 public final static String ProofElement_lname = "ProofElement";
	 public final static String ProofElement_qname = "iw200407:ProofElement";
	 public final static String ProofElement_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#ProofElement";
	 public final static Resource  ProofElement = ResourceFactory.createResource(ProofElement_uri);

	 public final static String LanguageAxiomSet_lname = "LanguageAxiomSet";
	 public final static String LanguageAxiomSet_qname = "iw200407:LanguageAxiomSet";
	 public final static String LanguageAxiomSet_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#LanguageAxiomSet";
	 public final static Resource  LanguageAxiomSet = ResourceFactory.createResource(LanguageAxiomSet_uri);

	 public final static String Document_lname = "Document";
	 public final static String Document_qname = "iw200407:Document";
	 public final static String Document_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Document";
	 public final static Resource  Document = ResourceFactory.createResource(Document_uri);

	 public final static String SourceUsage_lname = "SourceUsage";
	 public final static String SourceUsage_qname = "iw200407:SourceUsage";
	 public final static String SourceUsage_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#SourceUsage";
	 public final static Resource  SourceUsage = ResourceFactory.createResource(SourceUsage_uri);

	 public final static String Organization_lname = "Organization";
	 public final static String Organization_qname = "iw200407:Organization";
	 public final static String Organization_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Organization";
	 public final static Resource  Organization = ResourceFactory.createResource(Organization_uri);

	 public final static String TranslationRule_lname = "TranslationRule";
	 public final static String TranslationRule_qname = "iw200407:TranslationRule";
	 public final static String TranslationRule_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#TranslationRule";
	 public final static Resource  TranslationRule = ResourceFactory.createResource(TranslationRule_uri);

	 public final static String LearnedSourceUsage_lname = "LearnedSourceUsage";
	 public final static String LearnedSourceUsage_qname = "iw200407:LearnedSourceUsage";
	 public final static String LearnedSourceUsage_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#LearnedSourceUsage";
	 public final static Resource  LearnedSourceUsage = ResourceFactory.createResource(LearnedSourceUsage_uri);

	 public final static String InferenceRule_lname = "InferenceRule";
	 public final static String InferenceRule_qname = "iw200407:InferenceRule";
	 public final static String InferenceRule_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#InferenceRule";
	 public final static Resource  InferenceRule = ResourceFactory.createResource(InferenceRule_uri);

	 public final static String ModelElement_lname = "ModelElement";
	 public final static String ModelElement_qname = "iw200407:ModelElement";
	 public final static String ModelElement_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#ModelElement";
	 public final static Resource  ModelElement = ResourceFactory.createResource(ModelElement_uri);

	 public final static String TrustRelation_lname = "TrustRelation";
	 public final static String TrustRelation_qname = "iw200407:TrustRelation";
	 public final static String TrustRelation_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#TrustRelation";
	 public final static Resource  TrustRelation = ResourceFactory.createResource(TrustRelation_uri);

	 public final static String Mapping_lname = "Mapping";
	 public final static String Mapping_qname = "iw200407:Mapping";
	 public final static String Mapping_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Mapping";
	 public final static Resource  Mapping = ResourceFactory.createResource(Mapping_uri);

	 public final static String PrimitiveRule_lname = "PrimitiveRule";
	 public final static String PrimitiveRule_qname = "iw200407:PrimitiveRule";
	 public final static String PrimitiveRule_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#PrimitiveRule";
	 public final static Resource  PrimitiveRule = ResourceFactory.createResource(PrimitiveRule_uri);

	 public final static String DeclarativeRule_lname = "DeclarativeRule";
	 public final static String DeclarativeRule_qname = "iw200407:DeclarativeRule";
	 public final static String DeclarativeRule_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#DeclarativeRule";
	 public final static Resource  DeclarativeRule = ResourceFactory.createResource(DeclarativeRule_uri);

	 public final static String MethodRule_lname = "MethodRule";
	 public final static String MethodRule_qname = "iw200407:MethodRule";
	 public final static String MethodRule_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#MethodRule";
	 public final static Resource  MethodRule = ResourceFactory.createResource(MethodRule_uri);

	 public final static String DerivedRule_lname = "DerivedRule";
	 public final static String DerivedRule_qname = "iw200407:DerivedRule";
	 public final static String DerivedRule_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#DerivedRule";
	 public final static Resource  DerivedRule = ResourceFactory.createResource(DerivedRule_uri);

	 public final static String Agent_lname = "Agent";
	 public final static String Agent_qname = "iw200407:Agent";
	 public final static String Agent_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#Agent";
	 public final static Resource  Agent = ResourceFactory.createResource(Agent_uri);

	// Property (76)
	 public final static String mapFrom_lname = "mapFrom";
	 public final static String mapFrom_qname = "iw200407:mapFrom";
	 public final static String mapFrom_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#mapFrom";
	 public final static Property  mapFrom = ResourceFactory.createProperty(mapFrom_uri);

	 public final static String version_lname = "version";
	 public final static String version_qname = "iw200407:version";
	 public final static String version_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#version";
	 public final static Property  version = ResourceFactory.createProperty(version_uri);

	 public final static String hasSource_lname = "hasSource";
	 public final static String hasSource_qname = "iw200407:hasSource";
	 public final static String hasSource_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasSource";
	 public final static Property  hasSource = ResourceFactory.createProperty(hasSource_uri);

	 public final static String isExplanationOf_lname = "isExplanationOf";
	 public final static String isExplanationOf_qname = "iw200407:isExplanationOf";
	 public final static String isExplanationOf_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#isExplanationOf";
	 public final static Property  isExplanationOf = ResourceFactory.createProperty(isExplanationOf_uri);

	 public final static String hasShortPrettyName_lname = "hasShortPrettyName";
	 public final static String hasShortPrettyName_qname = "iw200407:hasShortPrettyName";
	 public final static String hasShortPrettyName_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasShortPrettyName";
	 public final static Property  hasShortPrettyName = ResourceFactory.createProperty(hasShortPrettyName_uri);

	 public final static String dataCollectionStart_lname = "dataCollectionStart";
	 public final static String dataCollectionStart_qname = "iw200407:dataCollectionStart";
	 public final static String dataCollectionStart_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#dataCollectionStart";
	 public final static Property  dataCollectionStart = ResourceFactory.createProperty(dataCollectionStart_uri);

	 public final static String hasTopic_lname = "hasTopic";
	 public final static String hasTopic_qname = "iw200407:hasTopic";
	 public final static String hasTopic_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasTopic";
	 public final static Property  hasTopic = ResourceFactory.createProperty(hasTopic_uri);

	 public final static String hasInferenceEngine_lname = "hasInferenceEngine";
	 public final static String hasInferenceEngine_qname = "iw200407:hasInferenceEngine";
	 public final static String hasInferenceEngine_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasInferenceEngine";
	 public final static Property  hasInferenceEngine = ResourceFactory.createProperty(hasInferenceEngine_uri);

	 public final static String isFromEngine_lname = "isFromEngine";
	 public final static String isFromEngine_qname = "iw200407:isFromEngine";
	 public final static String isFromEngine_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#isFromEngine";
	 public final static Property  isFromEngine = ResourceFactory.createProperty(isFromEngine_uri);

	 public final static String consequent_lname = "consequent";
	 public final static String consequent_qname = "iw200407:consequent";
	 public final static String consequent_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#consequent";
	 public final static Property  consequent = ResourceFactory.createProperty(consequent_uri);

	 public final static String hasReplacee_lname = "hasReplacee";
	 public final static String hasReplacee_qname = "iw200407:hasReplacee";
	 public final static String hasReplacee_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasReplacee";
	 public final static Property  hasReplacee = ResourceFactory.createProperty(hasReplacee_uri);

	 public final static String hasAudio_lname = "hasAudio";
	 public final static String hasAudio_qname = "iw200407:hasAudio";
	 public final static String hasAudio_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasAudio";
	 public final static Property  hasAudio = ResourceFactory.createProperty(hasAudio_uri);

	 public final static String hasTrustedParty_lname = "hasTrustedParty";
	 public final static String hasTrustedParty_qname = "iw200407:hasTrustedParty";
	 public final static String hasTrustedParty_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasTrustedParty";
	 public final static Property  hasTrustedParty = ResourceFactory.createProperty(hasTrustedParty_uri);

	 public final static String fromAnswerOrQuery_lname = "fromAnswerOrQuery";
	 public final static String fromAnswerOrQuery_qname = "iw200407:fromAnswerOrQuery";
	 public final static String fromAnswerOrQuery_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#fromAnswerOrQuery";
	 public final static Property  fromAnswerOrQuery = ResourceFactory.createProperty(fromAnswerOrQuery_uri);

	 public final static String hasAuthor_lname = "hasAuthor";
	 public final static String hasAuthor_qname = "iw200407:hasAuthor";
	 public final static String hasAuthor_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasAuthor";
	 public final static Property  hasAuthor = ResourceFactory.createProperty(hasAuthor_uri);

	 public final static String name_lname = "name";
	 public final static String name_qname = "iw200407:name";
	 public final static String name_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#name";
	 public final static Property  name = ResourceFactory.createProperty(name_uri);

	 public final static String month_lname = "month";
	 public final static String month_qname = "iw200407:month";
	 public final static String month_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#month";
	 public final static Property  month = ResourceFactory.createProperty(month_uri);

	 public final static String hasAnswer_lname = "hasAnswer";
	 public final static String hasAnswer_qname = "iw200407:hasAnswer";
	 public final static String hasAnswer_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasAnswer";
	 public final static Property  hasAnswer = ResourceFactory.createProperty(hasAnswer_uri);

	 public final static String queryContent_lname = "queryContent";
	 public final static String queryContent_qname = "iw200407:queryContent";
	 public final static String queryContent_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#queryContent";
	 public final static Property  queryContent = ResourceFactory.createProperty(queryContent_uri);

	 public final static String year_lname = "year";
	 public final static String year_qname = "iw200407:year";
	 public final static String year_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#year";
	 public final static Property  year = ResourceFactory.createProperty(year_uri);

	 public final static String hasProvenanceElement_lname = "hasProvenanceElement";
	 public final static String hasProvenanceElement_qname = "iw200407:hasProvenanceElement";
	 public final static String hasProvenanceElement_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasProvenanceElement";
	 public final static Property  hasProvenanceElement = ResourceFactory.createProperty(hasProvenanceElement_uri);

	 public final static String hasPrettyNameMapping_lname = "hasPrettyNameMapping";
	 public final static String hasPrettyNameMapping_qname = "iw200407:hasPrettyNameMapping";
	 public final static String hasPrettyNameMapping_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasPrettyNameMapping";
	 public final static Property  hasPrettyNameMapping = ResourceFactory.createProperty(hasPrettyNameMapping_uri);

	 public final static String forLanguage_lname = "forLanguage";
	 public final static String forLanguage_qname = "iw200407:forLanguage";
	 public final static String forLanguage_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#forLanguage";
	 public final static Property  forLanguage = ResourceFactory.createProperty(forLanguage_uri);

	 public final static String usageTime_lname = "usageTime";
	 public final static String usageTime_qname = "iw200407:usageTime";
	 public final static String usageTime_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#usageTime";
	 public final static Property  usageTime = ResourceFactory.createProperty(usageTime_uri);

	 public final static String hasTrustingParty_lname = "hasTrustingParty";
	 public final static String hasTrustingParty_qname = "iw200407:hasTrustingParty";
	 public final static String hasTrustingParty_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasTrustingParty";
	 public final static Property  hasTrustingParty = ResourceFactory.createProperty(hasTrustingParty_uri);

	 public final static String hasIndex_lname = "hasIndex";
	 public final static String hasIndex_qname = "iw200407:hasIndex";
	 public final static String hasIndex_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasIndex";
	 public final static Property  hasIndex = ResourceFactory.createProperty(hasIndex_uri);

	 public final static String day_lname = "day";
	 public final static String day_qname = "iw200407:day";
	 public final static String day_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#day";
	 public final static Property  day = ResourceFactory.createProperty(day_uri);

	 public final static String hasMetaBinding_lname = "hasMetaBinding";
	 public final static String hasMetaBinding_qname = "iw200407:hasMetaBinding";
	 public final static String hasMetaBinding_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasMetaBinding";
	 public final static Property  hasMetaBinding = ResourceFactory.createProperty(hasMetaBinding_uri);

	 public final static String englishDescriptionTemplate_lname = "englishDescriptionTemplate";
	 public final static String englishDescriptionTemplate_qname = "iw200407:englishDescriptionTemplate";
	 public final static String englishDescriptionTemplate_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#englishDescriptionTemplate";
	 public final static Property  englishDescriptionTemplate = ResourceFactory.createProperty(englishDescriptionTemplate_uri);

	 public final static String explanation_lname = "explanation";
	 public final static String explanation_qname = "iw200407:explanation";
	 public final static String explanation_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#explanation";
	 public final static Property  explanation = ResourceFactory.createProperty(explanation_uri);

	 public final static String hasLongPrettyName_lname = "hasLongPrettyName";
	 public final static String hasLongPrettyName_qname = "iw200407:hasLongPrettyName";
	 public final static String hasLongPrettyName_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasLongPrettyName";
	 public final static Property  hasLongPrettyName = ResourceFactory.createProperty(hasLongPrettyName_uri);

	 public final static String usesInferenceEngine_lname = "usesInferenceEngine";
	 public final static String usesInferenceEngine_qname = "iw200407:usesInferenceEngine";
	 public final static String usesInferenceEngine_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#usesInferenceEngine";
	 public final static Property  usesInferenceEngine = ResourceFactory.createProperty(usesInferenceEngine_uri);

	 public final static String hasDischarge_lname = "hasDischarge";
	 public final static String hasDischarge_qname = "iw200407:hasDischarge";
	 public final static String hasDischarge_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasDischarge";
	 public final static Property  hasDischarge = ResourceFactory.createProperty(hasDischarge_uri);

	 public final static String hasConclusion_lname = "hasConclusion";
	 public final static String hasConclusion_qname = "iw200407:hasConclusion";
	 public final static String hasConclusion_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasConclusion";
	 public final static Property  hasConclusion = ResourceFactory.createProperty(hasConclusion_uri);

	 public final static String isConsequentOf_lname = "isConsequentOf";
	 public final static String isConsequentOf_qname = "iw200407:isConsequentOf";
	 public final static String isConsequentOf_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#isConsequentOf";
	 public final static Property  isConsequentOf = ResourceFactory.createProperty(isConsequentOf_uri);

	 public final static String URL_lname = "URL";
	 public final static String URL_qname = "iw200407:URL";
	 public final static String URL_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#URL";
	 public final static Property  URL = ResourceFactory.createProperty(URL_uri);

	 public final static String submitter_lname = "submitter";
	 public final static String submitter_qname = "iw200407:submitter";
	 public final static String submitter_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#submitter";
	 public final static Property  submitter = ResourceFactory.createProperty(submitter_uri);

	 public final static String hasSourceUsage_lname = "hasSourceUsage";
	 public final static String hasSourceUsage_qname = "iw200407:hasSourceUsage";
	 public final static String hasSourceUsage_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasSourceUsage";
	 public final static Property  hasSourceUsage = ResourceFactory.createProperty(hasSourceUsage_uri);

	 public final static String hasFormat_lname = "hasFormat";
	 public final static String hasFormat_qname = "iw200407:hasFormat";
	 public final static String hasFormat_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasFormat";
	 public final static Property  hasFormat = ResourceFactory.createProperty(hasFormat_uri);

	 public final static String hasAxiom_lname = "hasAxiom";
	 public final static String hasAxiom_qname = "iw200407:hasAxiom";
	 public final static String hasAxiom_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasAxiom";
	 public final static Property  hasAxiom = ResourceFactory.createProperty(hasAxiom_uri);

	 public final static String spanFromByte_lname = "spanFromByte";
	 public final static String spanFromByte_qname = "iw200407:spanFromByte";
	 public final static String spanFromByte_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#spanFromByte";
	 public final static Property  spanFromByte = ResourceFactory.createProperty(spanFromByte_uri);

	 public final static String isQueryFor_lname = "isQueryFor";
	 public final static String isQueryFor_qname = "iw200407:isQueryFor";
	 public final static String isQueryFor_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#isQueryFor";
	 public final static Property  isQueryFor = ResourceFactory.createProperty(isQueryFor_uri);

	 public final static String ruleNodeSet_lname = "ruleNodeSet";
	 public final static String ruleNodeSet_qname = "iw200407:ruleNodeSet";
	 public final static String ruleNodeSet_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#ruleNodeSet";
	 public final static Property  ruleNodeSet = ResourceFactory.createProperty(ruleNodeSet_uri);

	 public final static String hasOriginalContent_lname = "hasOriginalContent";
	 public final static String hasOriginalContent_qname = "iw200407:hasOriginalContent";
	 public final static String hasOriginalContent_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasOriginalContent";
	 public final static Property  hasOriginalContent = ResourceFactory.createProperty(hasOriginalContent_uri);

	 public final static String dataCollectionEnd_lname = "dataCollectionEnd";
	 public final static String dataCollectionEnd_qname = "iw200407:dataCollectionEnd";
	 public final static String dataCollectionEnd_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#dataCollectionEnd";
	 public final static Property  dataCollectionEnd = ResourceFactory.createProperty(dataCollectionEnd_uri);

	 public final static String inferenceEngineRule_lname = "inferenceEngineRule";
	 public final static String inferenceEngineRule_qname = "iw200407:inferenceEngineRule";
	 public final static String inferenceEngineRule_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#inferenceEngineRule";
	 public final static Property  inferenceEngineRule = ResourceFactory.createProperty(inferenceEngineRule_uri);

	 public final static String spanToByte_lname = "spanToByte";
	 public final static String spanToByte_qname = "iw200407:spanToByte";
	 public final static String spanToByte_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#spanToByte";
	 public final static Property  spanToByte = ResourceFactory.createProperty(spanToByte_uri);

	 public final static String hasTrustValue_lname = "hasTrustValue";
	 public final static String hasTrustValue_qname = "iw200407:hasTrustValue";
	 public final static String hasTrustValue_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasTrustValue";
	 public final static Property  hasTrustValue = ResourceFactory.createProperty(hasTrustValue_uri);

	 public final static String mapTo_lname = "mapTo";
	 public final static String mapTo_qname = "iw200407:mapTo";
	 public final static String mapTo_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#mapTo";
	 public final static Property  mapTo = ResourceFactory.createProperty(mapTo_uri);

	 public final static String hasAntecedent_lname = "hasAntecedent";
	 public final static String hasAntecedent_qname = "iw200407:hasAntecedent";
	 public final static String hasAntecedent_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasAntecedent";
	 public final static Property  hasAntecedent = ResourceFactory.createProperty(hasAntecedent_uri);

	 public final static String hasRule_lname = "hasRule";
	 public final static String hasRule_qname = "iw200407:hasRule";
	 public final static String hasRule_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasRule";
	 public final static Property  hasRule = ResourceFactory.createProperty(hasRule_uri);

	 public final static String fromQuery_lname = "fromQuery";
	 public final static String fromQuery_qname = "iw200407:fromQuery";
	 public final static String fromQuery_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#fromQuery";
	 public final static Property  fromQuery = ResourceFactory.createProperty(fromQuery_uri);

	 public final static String toExpression_lname = "toExpression";
	 public final static String toExpression_qname = "iw200407:toExpression";
	 public final static String toExpression_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#toExpression";
	 public final static Property  toExpression = ResourceFactory.createProperty(toExpression_uri);

	 public final static String fromAnswer_lname = "fromAnswer";
	 public final static String fromAnswer_qname = "iw200407:fromAnswer";
	 public final static String fromAnswer_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#fromAnswer";
	 public final static Property  fromAnswer = ResourceFactory.createProperty(fromAnswer_uri);

	 public final static String hasEnglishString_lname = "hasEnglishString";
	 public final static String hasEnglishString_qname = "iw200407:hasEnglishString";
	 public final static String hasEnglishString_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasEnglishString";
	 public final static Property  hasEnglishString = ResourceFactory.createProperty(hasEnglishString_uri);

	 public final static String hasLanguage_lname = "hasLanguage";
	 public final static String hasLanguage_qname = "iw200407:hasLanguage";
	 public final static String hasLanguage_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasLanguage";
	 public final static Property  hasLanguage = ResourceFactory.createProperty(hasLanguage_uri);

	 public final static String firstSubmissionDate_lname = "firstSubmissionDate";
	 public final static String firstSubmissionDate_qname = "iw200407:firstSubmissionDate";
	 public final static String firstSubmissionDate_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#firstSubmissionDate";
	 public final static Property  firstSubmissionDate = ResourceFactory.createProperty(firstSubmissionDate_uri);

	 public final static String hasStartTime_lname = "hasStartTime";
	 public final static String hasStartTime_qname = "iw200407:hasStartTime";
	 public final static String hasStartTime_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasStartTime";
	 public final static Property  hasStartTime = ResourceFactory.createProperty(hasStartTime_uri);

	 public final static String toLanguage_lname = "toLanguage";
	 public final static String toLanguage_qname = "iw200407:toLanguage";
	 public final static String toLanguage_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#toLanguage";
	 public final static Property  toLanguage = ResourceFactory.createProperty(toLanguage_uri);

	 public final static String hasImage_lname = "hasImage";
	 public final static String hasImage_qname = "iw200407:hasImage";
	 public final static String hasImage_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasImage";
	 public final static Property  hasImage = ResourceFactory.createProperty(hasImage_uri);

	 public final static String ruleSpec_lname = "ruleSpec";
	 public final static String ruleSpec_qname = "iw200407:ruleSpec";
	 public final static String ruleSpec_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#ruleSpec";
	 public final static Property  ruleSpec = ResourceFactory.createProperty(ruleSpec_uri);

	 public final static String fromExpression_lname = "fromExpression";
	 public final static String fromExpression_qname = "iw200407:fromExpression";
	 public final static String fromExpression_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#fromExpression";
	 public final static Property  fromExpression = ResourceFactory.createProperty(fromExpression_uri);

	 public final static String hasMember_lname = "hasMember";
	 public final static String hasMember_qname = "iw200407:hasMember";
	 public final static String hasMember_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasMember";
	 public final static Property  hasMember = ResourceFactory.createProperty(hasMember_uri);

	 public final static String escapeCharacter_lname = "escapeCharacter";
	 public final static String escapeCharacter_qname = "iw200407:escapeCharacter";
	 public final static String escapeCharacter_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#escapeCharacter";
	 public final static Property  escapeCharacter = ResourceFactory.createProperty(escapeCharacter_uri);

	 public final static String fromLanguage_lname = "fromLanguage";
	 public final static String fromLanguage_qname = "iw200407:fromLanguage";
	 public final static String fromLanguage_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#fromLanguage";
	 public final static Property  fromLanguage = ResourceFactory.createProperty(fromLanguage_uri);

	 public final static String hasEndTime_lname = "hasEndTime";
	 public final static String hasEndTime_qname = "iw200407:hasEndTime";
	 public final static String hasEndTime_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasEndTime";
	 public final static Property  hasEndTime = ResourceFactory.createProperty(hasEndTime_uri);

	 public final static String lastSubmissionDate_lname = "lastSubmissionDate";
	 public final static String lastSubmissionDate_qname = "iw200407:lastSubmissionDate";
	 public final static String lastSubmissionDate_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#lastSubmissionDate";
	 public final static Property  lastSubmissionDate = ResourceFactory.createProperty(lastSubmissionDate_uri);

	 public final static String hasAnswerPattern_lname = "hasAnswerPattern";
	 public final static String hasAnswerPattern_qname = "iw200407:hasAnswerPattern";
	 public final static String hasAnswerPattern_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasAnswerPattern";
	 public final static Property  hasAnswerPattern = ResourceFactory.createProperty(hasAnswerPattern_uri);

	 public final static String verificationMethod_lname = "verificationMethod";
	 public final static String verificationMethod_qname = "iw200407:verificationMethod";
	 public final static String verificationMethod_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#verificationMethod";
	 public final static Property  verificationMethod = ResourceFactory.createProperty(verificationMethod_uri);

	 public final static String englishDescription_lname = "englishDescription";
	 public final static String englishDescription_qname = "iw200407:englishDescription";
	 public final static String englishDescription_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#englishDescription";
	 public final static Property  englishDescription = ResourceFactory.createProperty(englishDescription_uri);

	 public final static String hasPrettyName_lname = "hasPrettyName";
	 public final static String hasPrettyName_qname = "iw200407:hasPrettyName";
	 public final static String hasPrettyName_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasPrettyName";
	 public final static Property  hasPrettyName = ResourceFactory.createProperty(hasPrettyName_uri);

	 public final static String questionContent_lname = "questionContent";
	 public final static String questionContent_qname = "iw200407:questionContent";
	 public final static String questionContent_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#questionContent";
	 public final static Property  questionContent = ResourceFactory.createProperty(questionContent_uri);

	 public final static String usageQuery_lname = "usageQuery";
	 public final static String usageQuery_qname = "iw200407:usageQuery";
	 public final static String usageQuery_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#usageQuery";
	 public final static Property  usageQuery = ResourceFactory.createProperty(usageQuery_uri);

	 public final static String englishExample_lname = "englishExample";
	 public final static String englishExample_qname = "iw200407:englishExample";
	 public final static String englishExample_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#englishExample";
	 public final static Property  englishExample = ResourceFactory.createProperty(englishExample_uri);

	 public final static String axiomContent_lname = "axiomContent";
	 public final static String axiomContent_qname = "iw200407:axiomContent";
	 public final static String axiomContent_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#axiomContent";
	 public final static Property  axiomContent = ResourceFactory.createProperty(axiomContent_uri);

	 public final static String hasVariableMapping_lname = "hasVariableMapping";
	 public final static String hasVariableMapping_qname = "iw200407:hasVariableMapping";
	 public final static String hasVariableMapping_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#hasVariableMapping";
	 public final static Property  hasVariableMapping = ResourceFactory.createProperty(hasVariableMapping_uri);

	// Instance (2)
	 public final static String KSL_lname = "KSL";
	 public final static String KSL_qname = "iw200407:KSL";
	 public final static String KSL_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#KSL";
	 public final static Resource  KSL = ResourceFactory.createResource(KSL_uri);

	 public final static String DirectAssertion_lname = "DirectAssertion";
	 public final static String DirectAssertion_qname = "iw200407:DirectAssertion";
	 public final static String DirectAssertion_uri = "http://inferenceweb.stanford.edu/2004/07/iw.owl#DirectAssertion";
	 public final static Resource  DirectAssertion = ResourceFactory.createResource(DirectAssertion_uri);



}


 
