/**
 * RM.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Thu Jul 09 18:06:06 EDT 2009
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  sw4j.app.servlet.vocabulary;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  RDF Metadata Ontology@en-US
 *   	comment:   This ontology defines metadata about RDF related concepts. This ontology is create by Li Ding (http://www.cs.rpi.edu/~dingl/).
  @en-US
 */
public class RM{

    protected static final String NS = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#";

    public static final String getURI(){ return NS; }

	// Class (2)
	 public final static String SemanticWebDocument_lname = "SemanticWebDocument";
	 public final static String SemanticWebDocument_qname = "rm:SemanticWebDocument";
	 public final static String SemanticWebDocument_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#SemanticWebDocument";
	 public final static Resource  SemanticWebDocument = ResourceFactory.createResource(SemanticWebDocument_uri);

	 public final static String GrammarRDF_lname = "GrammarRDF";
	 public final static String GrammarRDF_qname = "rm:GrammarRDF";
	 public final static String GrammarRDF_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#GrammarRDF";
	 public final static Resource  GrammarRDF = ResourceFactory.createResource(GrammarRDF_uri);

	// Property (8)
	 public final static String hasEncoding_lname = "hasEncoding";
	 public final static String hasEncoding_qname = "rm:hasEncoding";
	 public final static String hasEncoding_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#hasEncoding";
	 public final static Property  hasEncoding = ResourceFactory.createProperty(hasEncoding_uri);

	 public final static String isEmbedded_lname = "isEmbedded";
	 public final static String isEmbedded_qname = "rm:isEmbedded";
	 public final static String isEmbedded_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#isEmbedded";
	 public final static Property  isEmbedded = ResourceFactory.createProperty(isEmbedded_uri);

	 public final static String hasMd5sum_lname = "hasMd5sum";
	 public final static String hasMd5sum_qname = "rm:hasMd5sum";
	 public final static String hasMd5sum_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#hasMd5sum";
	 public final static Property  hasMd5sum = ResourceFactory.createProperty(hasMd5sum_uri);

	 public final static String hasFiletype_lname = "hasFiletype";
	 public final static String hasFiletype_qname = "rm:hasFiletype";
	 public final static String hasFiletype_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#hasFiletype";
	 public final static Property  hasFiletype = ResourceFactory.createProperty(hasFiletype_uri);

	 public final static String hasCntTriple_lname = "hasCntTriple";
	 public final static String hasCntTriple_qname = "rm:hasCntTriple";
	 public final static String hasCntTriple_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#hasCntTriple";
	 public final static Property  hasCntTriple = ResourceFactory.createProperty(hasCntTriple_uri);

	 public final static String hasRDFSyntax_lname = "hasRDFSyntax";
	 public final static String hasRDFSyntax_qname = "rm:hasRDFSyntax";
	 public final static String hasRDFSyntax_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#hasRDFSyntax";
	 public final static Property  hasRDFSyntax = ResourceFactory.createProperty(hasRDFSyntax_uri);

	 public final static String hasLength_lname = "hasLength";
	 public final static String hasLength_qname = "rm:hasLength";
	 public final static String hasLength_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#hasLength";
	 public final static Property  hasLength = ResourceFactory.createProperty(hasLength_uri);

	 public final static String isRDF_lname = "isRDF";
	 public final static String isRDF_qname = "rm:isRDF";
	 public final static String isRDF_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#isRDF";
	 public final static Property  isRDF = ResourceFactory.createProperty(isRDF_uri);

	// Instance (5)
	 public final static String Turtle_lname = "Turtle";
	 public final static String Turtle_qname = "rm:Turtle";
	 public final static String Turtle_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#Turtle";
	 public final static Resource  Turtle = ResourceFactory.createResource(Turtle_uri);

	 public final static String RDFa_lname = "RDFa";
	 public final static String RDFa_qname = "rm:RDFa";
	 public final static String RDFa_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#RDFa";
	 public final static Resource  RDFa = ResourceFactory.createResource(RDFa_uri);

	 public final static String RDFXML_lname = "RDFXML";
	 public final static String RDFXML_qname = "rm:RDFXML";
	 public final static String RDFXML_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#RDFXML";
	 public final static Resource  RDFXML = ResourceFactory.createResource(RDFXML_uri);

	 public final static String NTriples_lname = "NTriples";
	 public final static String NTriples_qname = "rm:NTriples";
	 public final static String NTriples_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#NTriples";
	 public final static Resource  NTriples = ResourceFactory.createResource(NTriples_uri);

	 public final static String N3_lname = "N3";
	 public final static String N3_qname = "rm:N3";
	 public final static String N3_uri = "http://tw.rpi.edu/2009/sw/rdf-metadata.owl#N3";
	 public final static Resource  N3 = ResourceFactory.createResource(N3_uri);



}


 
