package sw4j.task.rdf;

import static org.junit.Assert.*;

import org.junit.Test;

import sw4j.task.load.DataTaskLoadHttp;
import sw4j.task.load.ToolLoadHttp;
import sw4j.util.ToolSafe;


public class ToolMarkupDetectorTest {

	
	@Test
	public void test_classify() {
	  String [][] aryURL = new String[][]{
			  {"http://www.w3.org/TR/rdf-schema",""+ToolMarkupDetector.FORMAT_XML},
			 
		  {"http://purl.org/dc/elements/1.1/", ""+ToolMarkupDetector.FORMAT_RDFXML},
		  {"http://www.cs.rpi.edu/~dingl/foaf.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
		  {"http://bclary.com/2004/03/15/22-rdf-syntax-ns.rdfs", ""+ToolMarkupDetector.FORMAT_HTML},   // no rdf anymore
		  {"http://www.mindswap.org/2003/submit-rdf/papers.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
		  {"http://www.w3.org/2001/09/soap-ntriples/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},

		  {"http://radio.weblogs.com/0001011/rss.xml",""+ToolMarkupDetector.FORMAT_XML},
		  {"http://purl.org/vocab/bio/0.1/",""+ToolMarkupDetector.FORMAT_XML},

		  {"http://catless.ncl.ac.uk/rivets.rdf",""+ToolMarkupDetector.FORMAT_RDFXML},
		  {"http://agents.umbc.edu/awchannel.rdf",""+ToolMarkupDetector.FORMAT_RDFXML},
			
		  
		  {"http://distrowatch.com/news/dw.rdf",""+ToolMarkupDetector.FORMAT_RDFXML},//FORMAT_HTML}, // this is an html file with rdf file extension
		  
		  {"http://java.sun.com/j2se/1.4.2/docs/api/org/xml/sax/ErrorHandler.html",""+ToolMarkupDetector.FORMAT_HTML},
		  {"http://web.resource.org/rss/1.0/modules/syndication/",""+ToolMarkupDetector.FORMAT_HTML},
		  {"http://webns.net/mvcb/",""+ToolMarkupDetector.FORMAT_HTML},
		  {"http://www.skallagrigg.org/",""+ToolMarkupDetector.FORMAT_HTML},
//			  {"http://xmlns.com/wordnet/1.6/",""+ToolMarkupDetector.FORMAT_HTML},

		 // {"http://139.91.183.30:9090/RDF/VRP/Examples/rdf-schema.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML}, 
		  {"http://www.daml.org/2003/11/swrl/swrl.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML}, 
		  {"http://annotation.semanticweb.org/iswc/iswc.owl", ""+ToolMarkupDetector.FORMAT_RDFXML},	
		  //{"http://www.alib.jp/personal/foaf.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
		  //{"http://basilides.perlmonk.org/foaf.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
		  {"http://barcelona.indymedia.org/features.1-0.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
		  {"http://daichanzeyo.cocolog-nifty.com/0403/index.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
		  {"http://ilrt.org/discovery/2001/06/schemas/swws/index.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},

			//a special rdf/xml embeded in xml, jena can parse it correctly.
		  {	"http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test005.rdf",""+ToolMarkupDetector.FORMAT_RDFXML},	
		  
		  
		  {	"http://creativecommons.org/licenses/by/2.0/",""+ToolMarkupDetector.FORMAT_HTML_EMBED_RDFXML},		//[-,+] rdf in comment section

	  };

	  for (int i=0; i<aryURL.length; i++){
		  String szURL = aryURL[i][0];
		  DataTaskLoadHttp task = ToolLoadHttp.loadUrl(szURL);
		  if (null==task){
			  System.out.println("crawler failure: "+szURL);
			  continue;
		  }
		  
		  if (!task.isLoadSucceed()){
			  System.out.println("download failed: " + szURL);
			  continue;
		  }
		  
		  if (ToolSafe.isEmpty(task.getContent()))
			  continue;
		  
		  //System.out.println(ToolWeb.removeHtmlComment(task.getContent()));
		  int expected_ret = ToolMarkupDetector.guessFormat(null, null, szURL, null);
		  int ret = ToolMarkupDetector.guessFormat(task.getContent(), expected_ret);
		  if ( !aryURL[i][1].equals(""+ret)){
			  System.out.println(szURL);
			  System.out.println ("expected: "+ ToolMarkupDetector.FORMAT_NAME[ Integer.parseInt(aryURL[i][1]) ][0]);
			  System.out.println ("found: "+ToolMarkupDetector.FORMAT_NAME[ret][0]);
			  fail();
		  }
		  
	  }
	}
	
	@Test
	public void test_classify_rdf_test() {
		ToolMarkupDetector.debug =true;
		String [][] aryURL = new String[][]{
			{"http://purl.org/dc/elements/1.1/", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/amp-in-url/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/amp-in-url/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/amp-in-url/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes-intensional/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes-intensional/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes-intensional/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/empty.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test002b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test003a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test003b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test004a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test004b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test004c.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test005a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test005b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test006.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test007a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test007b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test008a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test008b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test009a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test009b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test010.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test011a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/datatypes/test011b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/entailment", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/entailment/etc001.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/entailment/etc001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/entailment/etc001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/entailment/rdf-facts.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/entailment/rdf-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/entailment/rdfs-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/animal-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/animal-simple.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/animal.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/authen.lemma.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/builtins.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/danb-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/danb.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/danc-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/danc.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/dtP.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/etc.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
//						{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/etc5-proof.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
  
						// this file does not contain any RDF content
	  		{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/etc5.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},

			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/gedcom-facts.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/gedcom-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/gedcom-relations-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/graph.axiom.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/graph.lemma.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/graph.proof.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/janet-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/lists-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/owl-facts.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/owl-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/owl-rules.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdf-facts.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdf-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdf-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdf-rules.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdfc25May-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdfc25May-test.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdfc25May.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdfd-facts.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdfd-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdfd-theory.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdfs-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdfs-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/rdfs-rules.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/subclass-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/subclass-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/subclass.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/subprop-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/subprop.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/test-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/tpoint-facts.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/tpoint-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/tpoint-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/varprop-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/varprop-result.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/wol-facts.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/ziv-query.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/euler/ziv.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/horst-01/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/horst-01/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/horst-01/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/horst-01/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/horst-01/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/ntriples/test.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/pfps-10/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/pfps-10/test001a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/pfps-10/test001b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-literals", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-literals/error001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-literals/error002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-literals/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-literals/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-literals/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-uris", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-uris/error001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-uris/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-uris/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-uris/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-uris/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-charmod-uris/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/error001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/error002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test006.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test007.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test007.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test008.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-containers-syntax-vs-schema/test008.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-element-not-mandatory/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-element-not-mandatory/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-element-not-mandatory/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/error0001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/error0002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/error0003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/error0004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/error0005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/error0006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/error0007.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/error0008.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/error0009.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0006.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0007.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0007.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0008.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0008.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0009.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0009.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0010.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0010.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0011.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0011.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0012.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0012.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0013.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0013.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0014.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdf-ns-prefix-confusion/test0014.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-abouteach", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-abouteach/error001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-abouteach/error002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-abouteach/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-difference-between-ID-and-about", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-difference-between-ID-and-about/error1.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-difference-between-ID-and-about/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-difference-between-ID-and-about/test1.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-difference-between-ID-and-about/test1.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-difference-between-ID-and-about/test2.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-difference-between-ID-and-about/test2.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-difference-between-ID-and-about/test3.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-difference-between-ID-and-about/test3.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-duplicate-member-props/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-duplicate-member-props/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-duplicate-member-props/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/error001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/error002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/error003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test006.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test007.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test008.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test009.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test009.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test010.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test011.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test011.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test012.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test012.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test013.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test013.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test014.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test014.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test015.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test016.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test016.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test017.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-empty-property-elements/test017.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-identity-anon-resources/test005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-literal-is-xml-structure/test005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/rel", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test006.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test007.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test007.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test008.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test008.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test009.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test009.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test010.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test010a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test010b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test011.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test011a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test011b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test012.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test012a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-nested-bagIDs/test012b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-not-id-and-resource-attr/test005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-para196/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-para196/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-para196/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-parseType", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-parseType/error001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-parseType/error002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-parseType/error003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-parseType/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-id", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-id/error001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-id/error002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-id/error003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-id/error004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-id/error005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-id/error006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-id/error007.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-id/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/all.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/all.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-007.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-008.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-009.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-010.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-011.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-012.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-013.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-014.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-015.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-016.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-017.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-018.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-019.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-020.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-021.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-025.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/error-026.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-006.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-007.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-007.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-008.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-008.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-009.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-009.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-010.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-010.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-011.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-011.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-012.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-012.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-013.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-013.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-014.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-014.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-015.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-015.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-016.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-016.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-017.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-017.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-018.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-018.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-019.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-019.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-020.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-020.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-021.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-021.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-022.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-022.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-023.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-023.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-024.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-024.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-025.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-025.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-026.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-026.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-027.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-027.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-028.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-028.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-029.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-029.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-030.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-030.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-031.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-031.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-032.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-032.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-033.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-033.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-034.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-034.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-035.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-035.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-036.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-036.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-037.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-037.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-038.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-039.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-040.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-041.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-041.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-042.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-043.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-044.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-045.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-046.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-046.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/test-047.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/warn-001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/warn-001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/warn-002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/warn-002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/warn-003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-rdf-names-use/warn-003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-reification-required/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-reification-required/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-reification-required/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-seq-representation/empty.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-seq-representation/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-seq-representation/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-seq-representation/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-seq-representation/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-seq-representation/test003a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-seq-representation/test003b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-seq-representation/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/error001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/error002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/error003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/error004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/error005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/error006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-syntax-incomplete/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-uri-substructure", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-uri-substructure/error001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-uri-substructure/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-uri-substructure/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-uri-substructure/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xml-literal-namespaces/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xml-literal-namespaces/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xml-literal-namespaces/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xml-literal-namespaces/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xml-literal-namespaces/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test006.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test007a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test007b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfms-xmllang/test007c.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-container-membership-superProperty/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-container-membership-superProperty/not1C.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-container-membership-superProperty/not1C.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-container-membership-superProperty/not1P.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-container-membership-superProperty/not1P.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/Manifest.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/Manifest.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/nonconclusions005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/nonconclusions006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/premises005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/premises006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/readme.txt", ""+ToolMarkupDetector.FORMAT_TEXT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-domain-and-range/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-entailment/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-entailment/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-entailment/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-no-cycles-in-subClassOf/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-no-cycles-in-subClassOf/test001", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-no-cycles-in-subClassOf/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-no-cycles-in-subClassOf/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-no-cycles-in-subPropertyOf/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-no-cycles-in-subPropertyOf/test001", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-no-cycles-in-subPropertyOf/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-no-cycles-in-subPropertyOf/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-subClassOf-a-Property/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-subClassOf-a-Property/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-subPropertyOf-semantics", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-subPropertyOf-semantics/Manifest.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-subPropertyOf-semantics/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-subPropertyOf-semantics/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-subPropertyOf-semantics/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-subPropertyOf-semantics/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-transitive-subSubProperty/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/rdfs-transitive-subSubProperty/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
//						{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/skeleton/manifestTail.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
//						{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/skeleton/positiveParserTest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/statement-entailment", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/statement-entailment/Manifest.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/statement-entailment/Manifest.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/statement-entailment/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/statement-entailment/test001a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/statement-entailment/test001b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/statement-entailment/test002a.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/statement-entailment/test002b.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema.n3", ""+ToolMarkupDetector.FORMAT_TEXT_N3},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/tex-01/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/tex-01/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/tex-01/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/unrecognised-xml-attributes/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/unrecognised-xml-attributes/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/unrecognised-xml-attributes/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/unrecognised-xml-attributes/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/unrecognised-xml-attributes/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/utils/ntc", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xml-canon/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xml-canon/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xml-canon/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase", ""+ToolMarkupDetector.FORMAT_HTML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test001.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test002.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test003.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test004.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test004.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test005.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test005.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test006.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test006.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test007.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test007.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test008.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test008.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test009.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test009.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test010.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test010.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test011.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test011.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test012.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test012.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test013.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test013.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test014.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test014.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test015.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test015.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test016.nt", ""+ToolMarkupDetector.FORMAT_TEXT_NT},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlbase/test016.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlsch-02/Manifest.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlsch-02/test001.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlsch-02/test002.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
			{ "http://www.w3.org/2000/10/rdf-tests/rdfcore/xmlsch-02/test003.rdf", ""+ToolMarkupDetector.FORMAT_RDFXML},
		  };

		  for (int i=0; i<aryURL.length; i++){
			  String szURL = aryURL[i][0];
			  DataTaskLoadHttp task = ToolLoadHttp.loadUrl(szURL);
			  if (null==task){
				  System.out.println("crawler failure: "+szURL);
				  continue;
			  }
			  
			  if (!task.isLoadSucceed()){
				  System.out.println("download failed: " + szURL);
				  continue;
			  }
			  
			  if (ToolSafe.isEmpty(task.getContent()))
				  continue;
			  
			  //System.out.println(ToolWeb.removeHtmlComment(task.getContent()));
			  int expected_ret = ToolMarkupDetector.guessFormat(null, null, szURL,null);
			  int ret = ToolMarkupDetector.guessFormat(task.getContent(), expected_ret);
			  if ( !aryURL[i][1].equals(""+ret)){
				  System.out.println(szURL);
				  System.out.println ("expected: "+aryURL[i][1]);
				  System.out.println ("found: "+ToolMarkupDetector.FORMAT_NAME[ret][0]);
				  fail();
			  }
		  }
		}
	
}
