/**
 * PMLR.java
 *
 *  This file is automatically generated by PML API 
 *	generated on  Mon Jun 29 06:25:49 EDT 2009
 *  
 *  @author: Li Ding (http://www.cs.rpi.edu/~dingl )
 *
 */
package  sw4j.vocabulary.pml;

import com.hp.hpl.jena.rdf.model.Resource;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.ResourceFactory;


/**
 *
 *  
 *  Ontology information 
 *   	label:  PML2 relation ontology@en
 *   	comment:   The relation part of PML2 ontology. @en
 */
public class PMLR{

    protected static final String NS = "http://inference-web.org/2.0/pml-relation.owl#";

    public static final String getURI(){ return NS; }

	// Class (1)
	 public final static String Step_lname = "Step";
	 public final static String Step_qname = "pmlr:Step";
	 public final static String Step_uri = "http://inference-web.org/2.0/pml-relation.owl#Step";
	 public final static Resource  Step = ResourceFactory.createResource(Step_uri);

	// Property (7)
	 public final static String hasPart_lname = "hasPart";
	 public final static String hasPart_qname = "pmlr:hasPart";
	 public final static String hasPart_uri = "http://inference-web.org/2.0/pml-relation.owl#hasPart";
	 public final static Property  hasPart = ResourceFactory.createProperty(hasPart_uri);

	 public final static String isPartOf_lname = "isPartOf";
	 public final static String isPartOf_qname = "pmlr:isPartOf";
	 public final static String isPartOf_uri = "http://inference-web.org/2.0/pml-relation.owl#isPartOf";
	 public final static Property  isPartOf = ResourceFactory.createProperty(isPartOf_uri);

	 public final static String hasCondition_lname = "hasCondition";
	 public final static String hasCondition_qname = "pmlr:hasCondition";
	 public final static String hasCondition_uri = "http://inference-web.org/2.0/pml-relation.owl#hasCondition";
	 public final static Property  hasCondition = ResourceFactory.createProperty(hasCondition_uri);

	 public final static String hasOutput_lname = "hasOutput";
	 public final static String hasOutput_qname = "pmlr:hasOutput";
	 public final static String hasOutput_uri = "http://inference-web.org/2.0/pml-relation.owl#hasOutput";
	 public final static Property  hasOutput = ResourceFactory.createProperty(hasOutput_uri);

	 public final static String hasOperation_lname = "hasOperation";
	 public final static String hasOperation_qname = "pmlr:hasOperation";
	 public final static String hasOperation_uri = "http://inference-web.org/2.0/pml-relation.owl#hasOperation";
	 public final static Property  hasOperation = ResourceFactory.createProperty(hasOperation_uri);

	 public final static String hasInput_lname = "hasInput";
	 public final static String hasInput_qname = "pmlr:hasInput";
	 public final static String hasInput_uri = "http://inference-web.org/2.0/pml-relation.owl#hasInput";
	 public final static Property  hasInput = ResourceFactory.createProperty(hasInput_uri);

	 public final static String dependsOn_lname = "dependsOn";
	 public final static String dependsOn_qname = "pmlr:dependsOn";
	 public final static String dependsOn_uri = "http://inference-web.org/2.0/pml-relation.owl#dependsOn";
	 public final static Property  dependsOn = ResourceFactory.createProperty(dependsOn_uri);

	// Instance (2)
	 public final static String necessary_condition_lname = "necessary_condition";
	 public final static String necessary_condition_qname = "pmlr:necessary_condition";
	 public final static String necessary_condition_uri = "http://inference-web.org/2.0/pml-relation.owl#necessary_condition";
	 public final static Resource  necessary_condition = ResourceFactory.createResource(necessary_condition_uri);

	 public final static String sufficient_condition_lname = "sufficient_condition";
	 public final static String sufficient_condition_qname = "pmlr:sufficient_condition";
	 public final static String sufficient_condition_uri = "http://inference-web.org/2.0/pml-relation.owl#sufficient_condition";
	 public final static Resource  sufficient_condition = ResourceFactory.createResource(sufficient_condition_uri);



}


 
